// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: packages/api/quip-matchmaker.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StatusResponse_Status int32

const (
	StatusResponse_IDLE      StatusResponse_Status = 0
	StatusResponse_SEARCHING StatusResponse_Status = 1
	StatusResponse_PLAYING   StatusResponse_Status = 2
)

// Enum value maps for StatusResponse_Status.
var (
	StatusResponse_Status_name = map[int32]string{
		0: "IDLE",
		1: "SEARCHING",
		2: "PLAYING",
	}
	StatusResponse_Status_value = map[string]int32{
		"IDLE":      0,
		"SEARCHING": 1,
		"PLAYING":   2,
	}
)

func (x StatusResponse_Status) Enum() *StatusResponse_Status {
	p := new(StatusResponse_Status)
	*p = x
	return p
}

func (x StatusResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StatusResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_packages_api_quip_matchmaker_proto_enumTypes[0].Descriptor()
}

func (StatusResponse_Status) Type() protoreflect.EnumType {
	return &file_packages_api_quip_matchmaker_proto_enumTypes[0]
}

func (x StatusResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StatusResponse_Status.Descriptor instead.
func (StatusResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_packages_api_quip_matchmaker_proto_rawDescGZIP(), []int{3, 0}
}

type StartQueueRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Gamemode string `protobuf:"bytes,1,opt,name=gamemode,proto3" json:"gamemode,omitempty"`
}

func (x *StartQueueRequest) Reset() {
	*x = StartQueueRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_packages_api_quip_matchmaker_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartQueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartQueueRequest) ProtoMessage() {}

func (x *StartQueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_packages_api_quip_matchmaker_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartQueueRequest.ProtoReflect.Descriptor instead.
func (*StartQueueRequest) Descriptor() ([]byte, []int) {
	return file_packages_api_quip_matchmaker_proto_rawDescGZIP(), []int{0}
}

func (x *StartQueueRequest) GetGamemode() string {
	if x != nil {
		return x.Gamemode
	}
	return ""
}

// Event message indicating change in queue status.
type QueueUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Identifies the entities whose queue has received an update.
	Targets []string `protobuf:"bytes,1,rep,name=targets,proto3" json:"targets,omitempty"`
	// Types that are assignable to Update:
	//
	//	*QueueUpdate_Stopped
	//	*QueueUpdate_Found
	Update isQueueUpdate_Update `protobuf_oneof:"update"`
}

func (x *QueueUpdate) Reset() {
	*x = QueueUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_packages_api_quip_matchmaker_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueueUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueUpdate) ProtoMessage() {}

func (x *QueueUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_packages_api_quip_matchmaker_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueUpdate.ProtoReflect.Descriptor instead.
func (*QueueUpdate) Descriptor() ([]byte, []int) {
	return file_packages_api_quip_matchmaker_proto_rawDescGZIP(), []int{1}
}

func (x *QueueUpdate) GetTargets() []string {
	if x != nil {
		return x.Targets
	}
	return nil
}

func (m *QueueUpdate) GetUpdate() isQueueUpdate_Update {
	if m != nil {
		return m.Update
	}
	return nil
}

func (x *QueueUpdate) GetStopped() string {
	if x, ok := x.GetUpdate().(*QueueUpdate_Stopped); ok {
		return x.Stopped
	}
	return ""
}

func (x *QueueUpdate) GetFound() *MatchDetails {
	if x, ok := x.GetUpdate().(*QueueUpdate_Found); ok {
		return x.Found
	}
	return nil
}

type isQueueUpdate_Update interface {
	isQueueUpdate_Update()
}

type QueueUpdate_Stopped struct {
	Stopped string `protobuf:"bytes,2,opt,name=stopped,proto3,oneof"`
}

type QueueUpdate_Found struct {
	Found *MatchDetails `protobuf:"bytes,3,opt,name=found,proto3,oneof"`
}

func (*QueueUpdate_Stopped) isQueueUpdate_Update() {}

func (*QueueUpdate_Found) isQueueUpdate_Update() {}

type MatchDetails struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Connection string `protobuf:"bytes,1,opt,name=connection,proto3" json:"connection,omitempty"`
}

func (x *MatchDetails) Reset() {
	*x = MatchDetails{}
	if protoimpl.UnsafeEnabled {
		mi := &file_packages_api_quip_matchmaker_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MatchDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchDetails) ProtoMessage() {}

func (x *MatchDetails) ProtoReflect() protoreflect.Message {
	mi := &file_packages_api_quip_matchmaker_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchDetails.ProtoReflect.Descriptor instead.
func (*MatchDetails) Descriptor() ([]byte, []int) {
	return file_packages_api_quip_matchmaker_proto_rawDescGZIP(), []int{2}
}

func (x *MatchDetails) GetConnection() string {
	if x != nil {
		return x.Connection
	}
	return ""
}

type StatusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status StatusResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=quip.matchmaker.StatusResponse_Status" json:"status,omitempty"`
	// Details about the match the user is currently playing in.
	Match *MatchDetails `protobuf:"bytes,2,opt,name=match,proto3,oneof" json:"match,omitempty"`
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_packages_api_quip_matchmaker_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_packages_api_quip_matchmaker_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_packages_api_quip_matchmaker_proto_rawDescGZIP(), []int{3}
}

func (x *StatusResponse) GetStatus() StatusResponse_Status {
	if x != nil {
		return x.Status
	}
	return StatusResponse_IDLE
}

func (x *StatusResponse) GetMatch() *MatchDetails {
	if x != nil {
		return x.Match
	}
	return nil
}

var File_packages_api_quip_matchmaker_proto protoreflect.FileDescriptor

var file_packages_api_quip_matchmaker_proto_rawDesc = []byte{
	0x0a, 0x22, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x73, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x71,
	0x75, 0x69, 0x70, 0x2d, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x6d, 0x61, 0x6b, 0x65, 0x72, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x71, 0x75, 0x69, 0x70, 0x2e, 0x6d, 0x61, 0x74, 0x63, 0x68,
	0x6d, 0x61, 0x6b, 0x65, 0x72, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x2f, 0x0a, 0x11, 0x53, 0x74, 0x61, 0x72, 0x74, 0x51, 0x75, 0x65, 0x75, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x67, 0x61, 0x6d, 0x65, 0x6d,
	0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x67, 0x61, 0x6d, 0x65, 0x6d,
	0x6f, 0x64, 0x65, 0x22, 0x84, 0x01, 0x0a, 0x0b, 0x51, 0x75, 0x65, 0x75, 0x65, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x73, 0x12, 0x1a, 0x0a,
	0x07, 0x73, 0x74, 0x6f, 0x70, 0x70, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00,
	0x52, 0x07, 0x73, 0x74, 0x6f, 0x70, 0x70, 0x65, 0x64, 0x12, 0x35, 0x0a, 0x05, 0x66, 0x6f, 0x75,
	0x6e, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x71, 0x75, 0x69, 0x70, 0x2e,
	0x6d, 0x61, 0x74, 0x63, 0x68, 0x6d, 0x61, 0x6b, 0x65, 0x72, 0x2e, 0x4d, 0x61, 0x74, 0x63, 0x68,
	0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x48, 0x00, 0x52, 0x05, 0x66, 0x6f, 0x75, 0x6e, 0x64,
	0x42, 0x08, 0x0a, 0x06, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x22, 0x2e, 0x0a, 0x0c, 0x4d, 0x61,
	0x74, 0x63, 0x68, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x6f,
	0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0xc4, 0x01, 0x0a, 0x0e, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3e, 0x0a,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x26, 0x2e,
	0x71, 0x75, 0x69, 0x70, 0x2e, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x6d, 0x61, 0x6b, 0x65, 0x72, 0x2e,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x38, 0x0a,
	0x05, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x71,
	0x75, 0x69, 0x70, 0x2e, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x6d, 0x61, 0x6b, 0x65, 0x72, 0x2e, 0x4d,
	0x61, 0x74, 0x63, 0x68, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x48, 0x00, 0x52, 0x05, 0x6d,
	0x61, 0x74, 0x63, 0x68, 0x88, 0x01, 0x01, 0x22, 0x2e, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x08, 0x0a, 0x04, 0x49, 0x44, 0x4c, 0x45, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x53,
	0x45, 0x41, 0x52, 0x43, 0x48, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x50, 0x4c,
	0x41, 0x59, 0x49, 0x4e, 0x47, 0x10, 0x02, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x6d, 0x61, 0x74, 0x63,
	0x68, 0x32, 0xd9, 0x01, 0x0a, 0x0a, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x6d, 0x61, 0x6b, 0x65, 0x72,
	0x12, 0x44, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x16, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x1f, 0x2e, 0x71, 0x75, 0x69, 0x70, 0x2e, 0x6d, 0x61, 0x74,
	0x63, 0x68, 0x6d, 0x61, 0x6b, 0x65, 0x72, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x48, 0x0a, 0x0a, 0x53, 0x74, 0x61, 0x72, 0x74, 0x51,
	0x75, 0x65, 0x75, 0x65, 0x12, 0x22, 0x2e, 0x71, 0x75, 0x69, 0x70, 0x2e, 0x6d, 0x61, 0x74, 0x63,
	0x68, 0x6d, 0x61, 0x6b, 0x65, 0x72, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x51, 0x75, 0x65, 0x75,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x12, 0x3b, 0x0a, 0x09, 0x53, 0x74, 0x6f, 0x70, 0x51, 0x75, 0x65, 0x75, 0x65, 0x12, 0x16, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x42, 0x32, 0x5a,
	0x30, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x47, 0x61, 0x6d, 0x62,
	0x69, 0x74, 0x4c, 0x4c, 0x43, 0x2f, 0x71, 0x75, 0x69, 0x70, 0x2f, 0x70, 0x61, 0x63, 0x6b, 0x61,
	0x67, 0x65, 0x73, 0x2f, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x6d, 0x61, 0x6b, 0x65, 0x72, 0x2f, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_packages_api_quip_matchmaker_proto_rawDescOnce sync.Once
	file_packages_api_quip_matchmaker_proto_rawDescData = file_packages_api_quip_matchmaker_proto_rawDesc
)

func file_packages_api_quip_matchmaker_proto_rawDescGZIP() []byte {
	file_packages_api_quip_matchmaker_proto_rawDescOnce.Do(func() {
		file_packages_api_quip_matchmaker_proto_rawDescData = protoimpl.X.CompressGZIP(file_packages_api_quip_matchmaker_proto_rawDescData)
	})
	return file_packages_api_quip_matchmaker_proto_rawDescData
}

var file_packages_api_quip_matchmaker_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_packages_api_quip_matchmaker_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_packages_api_quip_matchmaker_proto_goTypes = []interface{}{
	(StatusResponse_Status)(0), // 0: quip.matchmaker.StatusResponse.Status
	(*StartQueueRequest)(nil),  // 1: quip.matchmaker.StartQueueRequest
	(*QueueUpdate)(nil),        // 2: quip.matchmaker.QueueUpdate
	(*MatchDetails)(nil),       // 3: quip.matchmaker.MatchDetails
	(*StatusResponse)(nil),     // 4: quip.matchmaker.StatusResponse
	(*emptypb.Empty)(nil),      // 5: google.protobuf.Empty
}
var file_packages_api_quip_matchmaker_proto_depIdxs = []int32{
	3, // 0: quip.matchmaker.QueueUpdate.found:type_name -> quip.matchmaker.MatchDetails
	0, // 1: quip.matchmaker.StatusResponse.status:type_name -> quip.matchmaker.StatusResponse.Status
	3, // 2: quip.matchmaker.StatusResponse.match:type_name -> quip.matchmaker.MatchDetails
	5, // 3: quip.matchmaker.Matchmaker.GetStatus:input_type -> google.protobuf.Empty
	1, // 4: quip.matchmaker.Matchmaker.StartQueue:input_type -> quip.matchmaker.StartQueueRequest
	5, // 5: quip.matchmaker.Matchmaker.StopQueue:input_type -> google.protobuf.Empty
	4, // 6: quip.matchmaker.Matchmaker.GetStatus:output_type -> quip.matchmaker.StatusResponse
	5, // 7: quip.matchmaker.Matchmaker.StartQueue:output_type -> google.protobuf.Empty
	5, // 8: quip.matchmaker.Matchmaker.StopQueue:output_type -> google.protobuf.Empty
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_packages_api_quip_matchmaker_proto_init() }
func file_packages_api_quip_matchmaker_proto_init() {
	if File_packages_api_quip_matchmaker_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_packages_api_quip_matchmaker_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartQueueRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_packages_api_quip_matchmaker_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueueUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_packages_api_quip_matchmaker_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MatchDetails); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_packages_api_quip_matchmaker_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatusResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_packages_api_quip_matchmaker_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*QueueUpdate_Stopped)(nil),
		(*QueueUpdate_Found)(nil),
	}
	file_packages_api_quip_matchmaker_proto_msgTypes[3].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_packages_api_quip_matchmaker_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_packages_api_quip_matchmaker_proto_goTypes,
		DependencyIndexes: file_packages_api_quip_matchmaker_proto_depIdxs,
		EnumInfos:         file_packages_api_quip_matchmaker_proto_enumTypes,
		MessageInfos:      file_packages_api_quip_matchmaker_proto_msgTypes,
	}.Build()
	File_packages_api_quip_matchmaker_proto = out.File
	file_packages_api_quip_matchmaker_proto_rawDesc = nil
	file_packages_api_quip_matchmaker_proto_goTypes = nil
	file_packages_api_quip_matchmaker_proto_depIdxs = nil
}
