// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: matchmaker/backend.proto

package matchmaker

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MatchState int32

const (
	MatchState_MATCH_STATE_UNSPECIFIED MatchState = 0
	MatchState_MATCH_STATE_PENDING     MatchState = 1 // Match has been allocated and is waiting for connections.
	MatchState_MATCH_STATE_PLAYING     MatchState = 2 // Match is in progress.
	MatchState_MATCH_STATE_FINISHED    MatchState = 3 // Match has completed.
)

// Enum value maps for MatchState.
var (
	MatchState_name = map[int32]string{
		0: "MATCH_STATE_UNSPECIFIED",
		1: "MATCH_STATE_PENDING",
		2: "MATCH_STATE_PLAYING",
		3: "MATCH_STATE_FINISHED",
	}
	MatchState_value = map[string]int32{
		"MATCH_STATE_UNSPECIFIED": 0,
		"MATCH_STATE_PENDING":     1,
		"MATCH_STATE_PLAYING":     2,
		"MATCH_STATE_FINISHED":    3,
	}
)

func (x MatchState) Enum() *MatchState {
	p := new(MatchState)
	*p = x
	return p
}

func (x MatchState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MatchState) Descriptor() protoreflect.EnumDescriptor {
	return file_matchmaker_backend_proto_enumTypes[0].Descriptor()
}

func (MatchState) Type() protoreflect.EnumType {
	return &file_matchmaker_backend_proto_enumTypes[0]
}

func (x MatchState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MatchState.Descriptor instead.
func (MatchState) EnumDescriptor() ([]byte, []int) {
	return file_matchmaker_backend_proto_rawDescGZIP(), []int{0}
}

// MatchRoster specifies the players in a match.
// TODO: specify teams when team games are supported
type MatchRoster struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Players []string `protobuf:"bytes,2,rep,name=players,proto3" json:"players,omitempty"`
}

func (x *MatchRoster) Reset() {
	*x = MatchRoster{}
	if protoimpl.UnsafeEnabled {
		mi := &file_matchmaker_backend_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MatchRoster) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchRoster) ProtoMessage() {}

func (x *MatchRoster) ProtoReflect() protoreflect.Message {
	mi := &file_matchmaker_backend_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchRoster.ProtoReflect.Descriptor instead.
func (*MatchRoster) Descriptor() ([]byte, []int) {
	return file_matchmaker_backend_proto_rawDescGZIP(), []int{0}
}

func (x *MatchRoster) GetPlayers() []string {
	if x != nil {
		return x.Players
	}
	return nil
}

type AllocateMatchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MatchId    string             `protobuf:"bytes,1,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	GameConfig *GameConfiguration `protobuf:"bytes,2,opt,name=game_config,json=gameConfig,proto3" json:"game_config,omitempty"`
	Roster     *MatchRoster       `protobuf:"bytes,3,opt,name=roster,proto3" json:"roster,omitempty"`
}

func (x *AllocateMatchRequest) Reset() {
	*x = AllocateMatchRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_matchmaker_backend_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllocateMatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocateMatchRequest) ProtoMessage() {}

func (x *AllocateMatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_matchmaker_backend_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllocateMatchRequest.ProtoReflect.Descriptor instead.
func (*AllocateMatchRequest) Descriptor() ([]byte, []int) {
	return file_matchmaker_backend_proto_rawDescGZIP(), []int{1}
}

func (x *AllocateMatchRequest) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

func (x *AllocateMatchRequest) GetGameConfig() *GameConfiguration {
	if x != nil {
		return x.GameConfig
	}
	return nil
}

func (x *AllocateMatchRequest) GetRoster() *MatchRoster {
	if x != nil {
		return x.Roster
	}
	return nil
}

type FinishMatchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MatchId string `protobuf:"bytes,1,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
}

func (x *FinishMatchRequest) Reset() {
	*x = FinishMatchRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_matchmaker_backend_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FinishMatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishMatchRequest) ProtoMessage() {}

func (x *FinishMatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_matchmaker_backend_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishMatchRequest.ProtoReflect.Descriptor instead.
func (*FinishMatchRequest) Descriptor() ([]byte, []int) {
	return file_matchmaker_backend_proto_rawDescGZIP(), []int{2}
}

func (x *FinishMatchRequest) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

var File_matchmaker_backend_proto protoreflect.FileDescriptor

var file_matchmaker_backend_proto_rawDesc = []byte{
	0x0a, 0x18, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x6d, 0x61, 0x6b, 0x65, 0x72, 0x2f, 0x62, 0x61, 0x63,
	0x6b, 0x65, 0x6e, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x71, 0x75, 0x69, 0x70,
	0x2e, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x6d, 0x61, 0x6b, 0x65, 0x72, 0x1a, 0x19, 0x6d, 0x61, 0x74,
	0x63, 0x68, 0x6d, 0x61, 0x6b, 0x65, 0x72, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x27, 0x0a, 0x0b, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x52, 0x6f, 0x73, 0x74,
	0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x22, 0xac, 0x01, 0x0a,
	0x14, 0x41, 0x6c, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x65, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x49, 0x64,
	0x12, 0x43, 0x0a, 0x0b, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x71, 0x75, 0x69, 0x70, 0x2e, 0x6d, 0x61, 0x74,
	0x63, 0x68, 0x6d, 0x61, 0x6b, 0x65, 0x72, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0a, 0x67, 0x61, 0x6d, 0x65, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x34, 0x0a, 0x06, 0x72, 0x6f, 0x73, 0x74, 0x65, 0x72, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x71, 0x75, 0x69, 0x70, 0x2e, 0x6d, 0x61, 0x74,
	0x63, 0x68, 0x6d, 0x61, 0x6b, 0x65, 0x72, 0x2e, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x52, 0x6f, 0x73,
	0x74, 0x65, 0x72, 0x52, 0x06, 0x72, 0x6f, 0x73, 0x74, 0x65, 0x72, 0x22, 0x2f, 0x0a, 0x12, 0x46,
	0x69, 0x6e, 0x69, 0x73, 0x68, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x19, 0x0a, 0x08, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x49, 0x64, 0x2a, 0x75, 0x0a, 0x0a,
	0x4d, 0x61, 0x74, 0x63, 0x68, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x1b, 0x0a, 0x17, 0x4d, 0x41,
	0x54, 0x43, 0x48, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43,
	0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x17, 0x0a, 0x13, 0x4d, 0x41, 0x54, 0x43, 0x48,
	0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x50, 0x45, 0x4e, 0x44, 0x49, 0x4e, 0x47, 0x10, 0x01,
	0x12, 0x17, 0x0a, 0x13, 0x4d, 0x41, 0x54, 0x43, 0x48, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f,
	0x50, 0x4c, 0x41, 0x59, 0x49, 0x4e, 0x47, 0x10, 0x02, 0x12, 0x18, 0x0a, 0x14, 0x4d, 0x41, 0x54,
	0x43, 0x48, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x46, 0x49, 0x4e, 0x49, 0x53, 0x48, 0x45,
	0x44, 0x10, 0x03, 0x32, 0xac, 0x01, 0x0a, 0x07, 0x42, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x12,
	0x55, 0x0a, 0x0d, 0x41, 0x6c, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x65, 0x4d, 0x61, 0x74, 0x63, 0x68,
	0x12, 0x25, 0x2e, 0x71, 0x75, 0x69, 0x70, 0x2e, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x6d, 0x61, 0x6b,
	0x65, 0x72, 0x2e, 0x41, 0x6c, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x65, 0x4d, 0x61, 0x74, 0x63, 0x68,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x71, 0x75, 0x69, 0x70, 0x2e, 0x6d,
	0x61, 0x74, 0x63, 0x68, 0x6d, 0x61, 0x6b, 0x65, 0x72, 0x2e, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x44,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x4a, 0x0a, 0x0b, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68,
	0x4d, 0x61, 0x74, 0x63, 0x68, 0x12, 0x23, 0x2e, 0x71, 0x75, 0x69, 0x70, 0x2e, 0x6d, 0x61, 0x74,
	0x63, 0x68, 0x6d, 0x61, 0x6b, 0x65, 0x72, 0x2e, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x4d, 0x61,
	0x74, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x42, 0x2e, 0x5a, 0x2c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x47, 0x61, 0x6d, 0x62, 0x69, 0x74, 0x4c, 0x4c, 0x43, 0x2f, 0x71, 0x75, 0x69, 0x70, 0x2f,
	0x6c, 0x69, 0x62, 0x73, 0x2f, 0x70, 0x62, 0x2f, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x6d, 0x61, 0x6b,
	0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_matchmaker_backend_proto_rawDescOnce sync.Once
	file_matchmaker_backend_proto_rawDescData = file_matchmaker_backend_proto_rawDesc
)

func file_matchmaker_backend_proto_rawDescGZIP() []byte {
	file_matchmaker_backend_proto_rawDescOnce.Do(func() {
		file_matchmaker_backend_proto_rawDescData = protoimpl.X.CompressGZIP(file_matchmaker_backend_proto_rawDescData)
	})
	return file_matchmaker_backend_proto_rawDescData
}

var file_matchmaker_backend_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_matchmaker_backend_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_matchmaker_backend_proto_goTypes = []interface{}{
	(MatchState)(0),              // 0: quip.matchmaker.MatchState
	(*MatchRoster)(nil),          // 1: quip.matchmaker.MatchRoster
	(*AllocateMatchRequest)(nil), // 2: quip.matchmaker.AllocateMatchRequest
	(*FinishMatchRequest)(nil),   // 3: quip.matchmaker.FinishMatchRequest
	(*GameConfiguration)(nil),    // 4: quip.matchmaker.GameConfiguration
	(*MatchDetails)(nil),         // 5: quip.matchmaker.MatchDetails
	(*emptypb.Empty)(nil),        // 6: google.protobuf.Empty
}
var file_matchmaker_backend_proto_depIdxs = []int32{
	4, // 0: quip.matchmaker.AllocateMatchRequest.game_config:type_name -> quip.matchmaker.GameConfiguration
	1, // 1: quip.matchmaker.AllocateMatchRequest.roster:type_name -> quip.matchmaker.MatchRoster
	2, // 2: quip.matchmaker.Backend.AllocateMatch:input_type -> quip.matchmaker.AllocateMatchRequest
	3, // 3: quip.matchmaker.Backend.FinishMatch:input_type -> quip.matchmaker.FinishMatchRequest
	5, // 4: quip.matchmaker.Backend.AllocateMatch:output_type -> quip.matchmaker.MatchDetails
	6, // 5: quip.matchmaker.Backend.FinishMatch:output_type -> google.protobuf.Empty
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_matchmaker_backend_proto_init() }
func file_matchmaker_backend_proto_init() {
	if File_matchmaker_backend_proto != nil {
		return
	}
	file_matchmaker_messages_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_matchmaker_backend_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MatchRoster); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_matchmaker_backend_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AllocateMatchRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_matchmaker_backend_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FinishMatchRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_matchmaker_backend_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_matchmaker_backend_proto_goTypes,
		DependencyIndexes: file_matchmaker_backend_proto_depIdxs,
		EnumInfos:         file_matchmaker_backend_proto_enumTypes,
		MessageInfos:      file_matchmaker_backend_proto_msgTypes,
	}.Build()
	File_matchmaker_backend_proto = out.File
	file_matchmaker_backend_proto_rawDesc = nil
	file_matchmaker_backend_proto_goTypes = nil
	file_matchmaker_backend_proto_depIdxs = nil
}
