// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: matchmaker/extensions.proto

package matchmaker

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OMTicketExtension struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *OMTicketExtension) Reset() {
	*x = OMTicketExtension{}
	if protoimpl.UnsafeEnabled {
		mi := &file_matchmaker_extensions_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OMTicketExtension) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OMTicketExtension) ProtoMessage() {}

func (x *OMTicketExtension) ProtoReflect() protoreflect.Message {
	mi := &file_matchmaker_extensions_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OMTicketExtension.ProtoReflect.Descriptor instead.
func (*OMTicketExtension) Descriptor() ([]byte, []int) {
	return file_matchmaker_extensions_proto_rawDescGZIP(), []int{0}
}

type OMProfileExtension struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *OMProfileExtension) Reset() {
	*x = OMProfileExtension{}
	if protoimpl.UnsafeEnabled {
		mi := &file_matchmaker_extensions_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OMProfileExtension) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OMProfileExtension) ProtoMessage() {}

func (x *OMProfileExtension) ProtoReflect() protoreflect.Message {
	mi := &file_matchmaker_extensions_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OMProfileExtension.ProtoReflect.Descriptor instead.
func (*OMProfileExtension) Descriptor() ([]byte, []int) {
	return file_matchmaker_extensions_proto_rawDescGZIP(), []int{1}
}

type OMMatchExtension struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *OMMatchExtension) Reset() {
	*x = OMMatchExtension{}
	if protoimpl.UnsafeEnabled {
		mi := &file_matchmaker_extensions_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OMMatchExtension) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OMMatchExtension) ProtoMessage() {}

func (x *OMMatchExtension) ProtoReflect() protoreflect.Message {
	mi := &file_matchmaker_extensions_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OMMatchExtension.ProtoReflect.Descriptor instead.
func (*OMMatchExtension) Descriptor() ([]byte, []int) {
	return file_matchmaker_extensions_proto_rawDescGZIP(), []int{2}
}

type AgonesAnnotation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AgonesAnnotation) Reset() {
	*x = AgonesAnnotation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_matchmaker_extensions_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AgonesAnnotation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgonesAnnotation) ProtoMessage() {}

func (x *AgonesAnnotation) ProtoReflect() protoreflect.Message {
	mi := &file_matchmaker_extensions_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgonesAnnotation.ProtoReflect.Descriptor instead.
func (*AgonesAnnotation) Descriptor() ([]byte, []int) {
	return file_matchmaker_extensions_proto_rawDescGZIP(), []int{3}
}

var File_matchmaker_extensions_proto protoreflect.FileDescriptor

var file_matchmaker_extensions_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x6d, 0x61, 0x6b, 0x65, 0x72, 0x2f, 0x65, 0x78, 0x74,
	0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x71,
	0x75, 0x69, 0x70, 0x2e, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x6d, 0x61, 0x6b, 0x65, 0x72, 0x1a, 0x19,
	0x6d, 0x61, 0x74, 0x63, 0x68, 0x6d, 0x61, 0x6b, 0x65, 0x72, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x13, 0x0a, 0x11, 0x4f, 0x4d, 0x54,
	0x69, 0x63, 0x6b, 0x65, 0x74, 0x45, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x14,
	0x0a, 0x12, 0x4f, 0x4d, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x45, 0x78, 0x74, 0x65, 0x6e,
	0x73, 0x69, 0x6f, 0x6e, 0x22, 0x12, 0x0a, 0x10, 0x4f, 0x4d, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x45,
	0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x12, 0x0a, 0x10, 0x41, 0x67, 0x6f, 0x6e,
	0x65, 0x73, 0x41, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x2e, 0x5a, 0x2c,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x47, 0x61, 0x6d, 0x62, 0x69,
	0x74, 0x4c, 0x4c, 0x43, 0x2f, 0x71, 0x75, 0x69, 0x70, 0x2f, 0x6c, 0x69, 0x62, 0x73, 0x2f, 0x70,
	0x62, 0x2f, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x6d, 0x61, 0x6b, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_matchmaker_extensions_proto_rawDescOnce sync.Once
	file_matchmaker_extensions_proto_rawDescData = file_matchmaker_extensions_proto_rawDesc
)

func file_matchmaker_extensions_proto_rawDescGZIP() []byte {
	file_matchmaker_extensions_proto_rawDescOnce.Do(func() {
		file_matchmaker_extensions_proto_rawDescData = protoimpl.X.CompressGZIP(file_matchmaker_extensions_proto_rawDescData)
	})
	return file_matchmaker_extensions_proto_rawDescData
}

var file_matchmaker_extensions_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_matchmaker_extensions_proto_goTypes = []interface{}{
	(*OMTicketExtension)(nil),  // 0: quip.matchmaker.OMTicketExtension
	(*OMProfileExtension)(nil), // 1: quip.matchmaker.OMProfileExtension
	(*OMMatchExtension)(nil),   // 2: quip.matchmaker.OMMatchExtension
	(*AgonesAnnotation)(nil),   // 3: quip.matchmaker.AgonesAnnotation
}
var file_matchmaker_extensions_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_matchmaker_extensions_proto_init() }
func file_matchmaker_extensions_proto_init() {
	if File_matchmaker_extensions_proto != nil {
		return
	}
	file_matchmaker_messages_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_matchmaker_extensions_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OMTicketExtension); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_matchmaker_extensions_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OMProfileExtension); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_matchmaker_extensions_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OMMatchExtension); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_matchmaker_extensions_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AgonesAnnotation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_matchmaker_extensions_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_matchmaker_extensions_proto_goTypes,
		DependencyIndexes: file_matchmaker_extensions_proto_depIdxs,
		MessageInfos:      file_matchmaker_extensions_proto_msgTypes,
	}.Build()
	File_matchmaker_extensions_proto = out.File
	file_matchmaker_extensions_proto_rawDesc = nil
	file_matchmaker_extensions_proto_goTypes = nil
	file_matchmaker_extensions_proto_depIdxs = nil
}
