// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: matchmaker/frontend.proto

package matchmaker

import (
	status "google.golang.org/genproto/googleapis/rpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Action:
	//
	//	*Request_GetPlayer
	//	*Request_StartQueue
	//	*Request_StopQueue
	Action isRequest_Action `protobuf_oneof:"action"`
}

func (x *Request) Reset() {
	*x = Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_matchmaker_frontend_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_matchmaker_frontend_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_matchmaker_frontend_proto_rawDescGZIP(), []int{0}
}

func (m *Request) GetAction() isRequest_Action {
	if m != nil {
		return m.Action
	}
	return nil
}

func (x *Request) GetGetPlayer() *GetPlayer {
	if x, ok := x.GetAction().(*Request_GetPlayer); ok {
		return x.GetPlayer
	}
	return nil
}

func (x *Request) GetStartQueue() *StartQueue {
	if x, ok := x.GetAction().(*Request_StartQueue); ok {
		return x.StartQueue
	}
	return nil
}

func (x *Request) GetStopQueue() *StopQueue {
	if x, ok := x.GetAction().(*Request_StopQueue); ok {
		return x.StopQueue
	}
	return nil
}

type isRequest_Action interface {
	isRequest_Action()
}

type Request_GetPlayer struct {
	GetPlayer *GetPlayer `protobuf:"bytes,1,opt,name=get_player,json=getPlayer,proto3,oneof"`
}

type Request_StartQueue struct {
	StartQueue *StartQueue `protobuf:"bytes,2,opt,name=start_queue,json=startQueue,proto3,oneof"`
}

type Request_StopQueue struct {
	StopQueue *StopQueue `protobuf:"bytes,3,opt,name=stop_queue,json=stopQueue,proto3,oneof"`
}

func (*Request_GetPlayer) isRequest_Action() {}

func (*Request_StartQueue) isRequest_Action() {}

func (*Request_StopQueue) isRequest_Action() {}

// GetPlayer gets the details for the currently logged in player.
type GetPlayer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetPlayer) Reset() {
	*x = GetPlayer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_matchmaker_frontend_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPlayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayer) ProtoMessage() {}

func (x *GetPlayer) ProtoReflect() protoreflect.Message {
	mi := &file_matchmaker_frontend_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayer.ProtoReflect.Descriptor instead.
func (*GetPlayer) Descriptor() ([]byte, []int) {
	return file_matchmaker_frontend_proto_rawDescGZIP(), []int{1}
}

type StartQueue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Config *QueueConfiguration `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
}

func (x *StartQueue) Reset() {
	*x = StartQueue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_matchmaker_frontend_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartQueue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartQueue) ProtoMessage() {}

func (x *StartQueue) ProtoReflect() protoreflect.Message {
	mi := &file_matchmaker_frontend_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartQueue.ProtoReflect.Descriptor instead.
func (*StartQueue) Descriptor() ([]byte, []int) {
	return file_matchmaker_frontend_proto_rawDescGZIP(), []int{2}
}

func (x *StartQueue) GetConfig() *QueueConfiguration {
	if x != nil {
		return x.Config
	}
	return nil
}

type StopQueue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StopQueue) Reset() {
	*x = StopQueue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_matchmaker_frontend_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StopQueue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopQueue) ProtoMessage() {}

func (x *StopQueue) ProtoReflect() protoreflect.Message {
	mi := &file_matchmaker_frontend_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopQueue.ProtoReflect.Descriptor instead.
func (*StopQueue) Descriptor() ([]byte, []int) {
	return file_matchmaker_frontend_proto_rawDescGZIP(), []int{3}
}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Message:
	//
	//	*Response_Error
	//	*Response_Player
	//	*Response_StatusUpdate
	Message isResponse_Message `protobuf_oneof:"message"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_matchmaker_frontend_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_matchmaker_frontend_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_matchmaker_frontend_proto_rawDescGZIP(), []int{4}
}

func (m *Response) GetMessage() isResponse_Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (x *Response) GetError() *status.Status {
	if x, ok := x.GetMessage().(*Response_Error); ok {
		return x.Error
	}
	return nil
}

func (x *Response) GetPlayer() *Player {
	if x, ok := x.GetMessage().(*Response_Player); ok {
		return x.Player
	}
	return nil
}

func (x *Response) GetStatusUpdate() *StatusUpdate {
	if x, ok := x.GetMessage().(*Response_StatusUpdate); ok {
		return x.StatusUpdate
	}
	return nil
}

type isResponse_Message interface {
	isResponse_Message()
}

type Response_Error struct {
	// error is sent if any request failed.
	Error *status.Status `protobuf:"bytes,1,opt,name=error,proto3,oneof"`
}

type Response_Player struct {
	// Response to GetPlayer or any StateUpdate messages for friends.
	Player *Player `protobuf:"bytes,2,opt,name=player,proto3,oneof"`
}

type Response_StatusUpdate struct {
	// Status updates for the current player.
	StatusUpdate *StatusUpdate `protobuf:"bytes,4,opt,name=status_update,json=statusUpdate,proto3,oneof"`
}

func (*Response_Error) isResponse_Message() {}

func (*Response_Player) isResponse_Message() {}

func (*Response_StatusUpdate) isResponse_Message() {}

var File_matchmaker_frontend_proto protoreflect.FileDescriptor

var file_matchmaker_frontend_proto_rawDesc = []byte{
	0x0a, 0x19, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x6d, 0x61, 0x6b, 0x65, 0x72, 0x2f, 0x66, 0x72, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x71, 0x75, 0x69,
	0x70, 0x2e, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x6d, 0x61, 0x6b, 0x65, 0x72, 0x1a, 0x19, 0x6d, 0x61,
	0x74, 0x63, 0x68, 0x6d, 0x61, 0x6b, 0x65, 0x72, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x17, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x72, 0x70, 0x63, 0x2f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0xcd, 0x01, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3b, 0x0a, 0x0a,
	0x67, 0x65, 0x74, 0x5f, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x71, 0x75, 0x69, 0x70, 0x2e, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x6d, 0x61, 0x6b,
	0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x48, 0x00, 0x52, 0x09,
	0x67, 0x65, 0x74, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x3e, 0x0a, 0x0b, 0x73, 0x74, 0x61,
	0x72, 0x74, 0x5f, 0x71, 0x75, 0x65, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b,
	0x2e, 0x71, 0x75, 0x69, 0x70, 0x2e, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x6d, 0x61, 0x6b, 0x65, 0x72,
	0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x51, 0x75, 0x65, 0x75, 0x65, 0x48, 0x00, 0x52, 0x0a, 0x73,
	0x74, 0x61, 0x72, 0x74, 0x51, 0x75, 0x65, 0x75, 0x65, 0x12, 0x3b, 0x0a, 0x0a, 0x73, 0x74, 0x6f,
	0x70, 0x5f, 0x71, 0x75, 0x65, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x71, 0x75, 0x69, 0x70, 0x2e, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x6d, 0x61, 0x6b, 0x65, 0x72, 0x2e,
	0x53, 0x74, 0x6f, 0x70, 0x51, 0x75, 0x65, 0x75, 0x65, 0x48, 0x00, 0x52, 0x09, 0x73, 0x74, 0x6f,
	0x70, 0x51, 0x75, 0x65, 0x75, 0x65, 0x42, 0x08, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x22, 0x0b, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x22, 0x49, 0x0a,
	0x0a, 0x53, 0x74, 0x61, 0x72, 0x74, 0x51, 0x75, 0x65, 0x75, 0x65, 0x12, 0x3b, 0x0a, 0x06, 0x63,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x71, 0x75,
	0x69, 0x70, 0x2e, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x6d, 0x61, 0x6b, 0x65, 0x72, 0x2e, 0x51, 0x75,
	0x65, 0x75, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x22, 0x0b, 0x0a, 0x09, 0x53, 0x74, 0x6f, 0x70,
	0x51, 0x75, 0x65, 0x75, 0x65, 0x22, 0xba, 0x01, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x2a, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x12, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x48, 0x00, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x31,
	0x0a, 0x06, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17,
	0x2e, 0x71, 0x75, 0x69, 0x70, 0x2e, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x6d, 0x61, 0x6b, 0x65, 0x72,
	0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x48, 0x00, 0x52, 0x06, 0x70, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x12, 0x44, 0x0a, 0x0d, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x5f, 0x75, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x71, 0x75, 0x69, 0x70, 0x2e,
	0x6d, 0x61, 0x74, 0x63, 0x68, 0x6d, 0x61, 0x6b, 0x65, 0x72, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x48, 0x00, 0x52, 0x0c, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x09, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x32, 0x52, 0x0a, 0x0c, 0x51, 0x75, 0x69, 0x70, 0x46, 0x72, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x64, 0x12, 0x42, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x12, 0x18, 0x2e,
	0x71, 0x75, 0x69, 0x70, 0x2e, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x6d, 0x61, 0x6b, 0x65, 0x72, 0x2e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x71, 0x75, 0x69, 0x70, 0x2e, 0x6d,
	0x61, 0x74, 0x63, 0x68, 0x6d, 0x61, 0x6b, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x28, 0x01, 0x30, 0x01, 0x42, 0x2e, 0x5a, 0x2c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x47, 0x61, 0x6d, 0x62, 0x69, 0x74, 0x4c, 0x4c, 0x43, 0x2f, 0x71,
	0x75, 0x69, 0x70, 0x2f, 0x6c, 0x69, 0x62, 0x73, 0x2f, 0x70, 0x62, 0x2f, 0x6d, 0x61, 0x74, 0x63,
	0x68, 0x6d, 0x61, 0x6b, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_matchmaker_frontend_proto_rawDescOnce sync.Once
	file_matchmaker_frontend_proto_rawDescData = file_matchmaker_frontend_proto_rawDesc
)

func file_matchmaker_frontend_proto_rawDescGZIP() []byte {
	file_matchmaker_frontend_proto_rawDescOnce.Do(func() {
		file_matchmaker_frontend_proto_rawDescData = protoimpl.X.CompressGZIP(file_matchmaker_frontend_proto_rawDescData)
	})
	return file_matchmaker_frontend_proto_rawDescData
}

var file_matchmaker_frontend_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_matchmaker_frontend_proto_goTypes = []interface{}{
	(*Request)(nil),            // 0: quip.matchmaker.Request
	(*GetPlayer)(nil),          // 1: quip.matchmaker.GetPlayer
	(*StartQueue)(nil),         // 2: quip.matchmaker.StartQueue
	(*StopQueue)(nil),          // 3: quip.matchmaker.StopQueue
	(*Response)(nil),           // 4: quip.matchmaker.Response
	(*QueueConfiguration)(nil), // 5: quip.matchmaker.QueueConfiguration
	(*status.Status)(nil),      // 6: google.rpc.Status
	(*Player)(nil),             // 7: quip.matchmaker.Player
	(*StatusUpdate)(nil),       // 8: quip.matchmaker.StatusUpdate
}
var file_matchmaker_frontend_proto_depIdxs = []int32{
	1, // 0: quip.matchmaker.Request.get_player:type_name -> quip.matchmaker.GetPlayer
	2, // 1: quip.matchmaker.Request.start_queue:type_name -> quip.matchmaker.StartQueue
	3, // 2: quip.matchmaker.Request.stop_queue:type_name -> quip.matchmaker.StopQueue
	5, // 3: quip.matchmaker.StartQueue.config:type_name -> quip.matchmaker.QueueConfiguration
	6, // 4: quip.matchmaker.Response.error:type_name -> google.rpc.Status
	7, // 5: quip.matchmaker.Response.player:type_name -> quip.matchmaker.Player
	8, // 6: quip.matchmaker.Response.status_update:type_name -> quip.matchmaker.StatusUpdate
	0, // 7: quip.matchmaker.QuipFrontend.Connect:input_type -> quip.matchmaker.Request
	4, // 8: quip.matchmaker.QuipFrontend.Connect:output_type -> quip.matchmaker.Response
	8, // [8:9] is the sub-list for method output_type
	7, // [7:8] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_matchmaker_frontend_proto_init() }
func file_matchmaker_frontend_proto_init() {
	if File_matchmaker_frontend_proto != nil {
		return
	}
	file_matchmaker_messages_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_matchmaker_frontend_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_matchmaker_frontend_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPlayer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_matchmaker_frontend_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartQueue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_matchmaker_frontend_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StopQueue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_matchmaker_frontend_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_matchmaker_frontend_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*Request_GetPlayer)(nil),
		(*Request_StartQueue)(nil),
		(*Request_StopQueue)(nil),
	}
	file_matchmaker_frontend_proto_msgTypes[4].OneofWrappers = []interface{}{
		(*Response_Error)(nil),
		(*Response_Player)(nil),
		(*Response_StatusUpdate)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_matchmaker_frontend_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_matchmaker_frontend_proto_goTypes,
		DependencyIndexes: file_matchmaker_frontend_proto_depIdxs,
		MessageInfos:      file_matchmaker_frontend_proto_msgTypes,
	}.Build()
	File_matchmaker_frontend_proto = out.File
	file_matchmaker_frontend_proto_rawDesc = nil
	file_matchmaker_frontend_proto_goTypes = nil
	file_matchmaker_frontend_proto_depIdxs = nil
}
