// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: matchmaker/frontend.proto

package matchmaker

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	QuipFrontend_Connect_FullMethodName = "/quip.matchmaker.QuipFrontend/Connect"
)

// QuipFrontendClient is the client API for QuipFrontend service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QuipFrontendClient interface {
	// Connect is a long-lived rpc for clients to send queue actions and
	// receive queue updates.
	Connect(ctx context.Context, opts ...grpc.CallOption) (QuipFrontend_ConnectClient, error)
}

type quipFrontendClient struct {
	cc grpc.ClientConnInterface
}

func NewQuipFrontendClient(cc grpc.ClientConnInterface) QuipFrontendClient {
	return &quipFrontendClient{cc}
}

func (c *quipFrontendClient) Connect(ctx context.Context, opts ...grpc.CallOption) (QuipFrontend_ConnectClient, error) {
	stream, err := c.cc.NewStream(ctx, &QuipFrontend_ServiceDesc.Streams[0], QuipFrontend_Connect_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &quipFrontendConnectClient{stream}
	return x, nil
}

type QuipFrontend_ConnectClient interface {
	Send(*Request) error
	Recv() (*Response, error)
	grpc.ClientStream
}

type quipFrontendConnectClient struct {
	grpc.ClientStream
}

func (x *quipFrontendConnectClient) Send(m *Request) error {
	return x.ClientStream.SendMsg(m)
}

func (x *quipFrontendConnectClient) Recv() (*Response, error) {
	m := new(Response)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// QuipFrontendServer is the server API for QuipFrontend service.
// All implementations should embed UnimplementedQuipFrontendServer
// for forward compatibility
type QuipFrontendServer interface {
	// Connect is a long-lived rpc for clients to send queue actions and
	// receive queue updates.
	Connect(QuipFrontend_ConnectServer) error
}

// UnimplementedQuipFrontendServer should be embedded to have forward compatible implementations.
type UnimplementedQuipFrontendServer struct {
}

func (UnimplementedQuipFrontendServer) Connect(QuipFrontend_ConnectServer) error {
	return status.Errorf(codes.Unimplemented, "method Connect not implemented")
}

// UnsafeQuipFrontendServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QuipFrontendServer will
// result in compilation errors.
type UnsafeQuipFrontendServer interface {
	mustEmbedUnimplementedQuipFrontendServer()
}

func RegisterQuipFrontendServer(s grpc.ServiceRegistrar, srv QuipFrontendServer) {
	s.RegisterService(&QuipFrontend_ServiceDesc, srv)
}

func _QuipFrontend_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(QuipFrontendServer).Connect(&quipFrontendConnectServer{stream})
}

type QuipFrontend_ConnectServer interface {
	Send(*Response) error
	Recv() (*Request, error)
	grpc.ServerStream
}

type quipFrontendConnectServer struct {
	grpc.ServerStream
}

func (x *quipFrontendConnectServer) Send(m *Response) error {
	return x.ServerStream.SendMsg(m)
}

func (x *quipFrontendConnectServer) Recv() (*Request, error) {
	m := new(Request)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// QuipFrontend_ServiceDesc is the grpc.ServiceDesc for QuipFrontend service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var QuipFrontend_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "quip.matchmaker.QuipFrontend",
	HandlerType: (*QuipFrontendServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _QuipFrontend_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "matchmaker/frontend.proto",
}
