// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: matchmaker/manager.proto

package matchmaker

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	QuipManager_CreateMatch_FullMethodName = "/quip.matchmaker.QuipManager/CreateMatch"
	QuipManager_StartMatch_FullMethodName  = "/quip.matchmaker.QuipManager/StartMatch"
	QuipManager_CancelMatch_FullMethodName = "/quip.matchmaker.QuipManager/CancelMatch"
	QuipManager_FinishMatch_FullMethodName = "/quip.matchmaker.QuipManager/FinishMatch"
)

// QuipManagerClient is the client API for QuipManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QuipManagerClient interface {
	// CreateMatch should be called by gameservers when they are allocated. It will attempt
	// to mark all players in the roster as participants in the match.
	CreateMatch(ctx context.Context, in *CreateMatchRequest, opts ...grpc.CallOption) (*CreateMatchResponse, error)
	// StartMatch should be called when gameservers actually begin play.
	// For matches with a wager, this means after collecting the wager from all players.
	StartMatch(ctx context.Context, in *StartMatchRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// CancelMatch should be called if gameservers do not start play for any reason.
	CancelMatch(ctx context.Context, in *CancelMatchRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// FinishMatch should be called when gameservers finish play.
	FinishMatch(ctx context.Context, in *FinishMatchRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type quipManagerClient struct {
	cc grpc.ClientConnInterface
}

func NewQuipManagerClient(cc grpc.ClientConnInterface) QuipManagerClient {
	return &quipManagerClient{cc}
}

func (c *quipManagerClient) CreateMatch(ctx context.Context, in *CreateMatchRequest, opts ...grpc.CallOption) (*CreateMatchResponse, error) {
	out := new(CreateMatchResponse)
	err := c.cc.Invoke(ctx, QuipManager_CreateMatch_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quipManagerClient) StartMatch(ctx context.Context, in *StartMatchRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, QuipManager_StartMatch_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quipManagerClient) CancelMatch(ctx context.Context, in *CancelMatchRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, QuipManager_CancelMatch_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quipManagerClient) FinishMatch(ctx context.Context, in *FinishMatchRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, QuipManager_FinishMatch_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QuipManagerServer is the server API for QuipManager service.
// All implementations should embed UnimplementedQuipManagerServer
// for forward compatibility
type QuipManagerServer interface {
	// CreateMatch should be called by gameservers when they are allocated. It will attempt
	// to mark all players in the roster as participants in the match.
	CreateMatch(context.Context, *CreateMatchRequest) (*CreateMatchResponse, error)
	// StartMatch should be called when gameservers actually begin play.
	// For matches with a wager, this means after collecting the wager from all players.
	StartMatch(context.Context, *StartMatchRequest) (*emptypb.Empty, error)
	// CancelMatch should be called if gameservers do not start play for any reason.
	CancelMatch(context.Context, *CancelMatchRequest) (*emptypb.Empty, error)
	// FinishMatch should be called when gameservers finish play.
	FinishMatch(context.Context, *FinishMatchRequest) (*emptypb.Empty, error)
}

// UnimplementedQuipManagerServer should be embedded to have forward compatible implementations.
type UnimplementedQuipManagerServer struct {
}

func (UnimplementedQuipManagerServer) CreateMatch(context.Context, *CreateMatchRequest) (*CreateMatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateMatch not implemented")
}
func (UnimplementedQuipManagerServer) StartMatch(context.Context, *StartMatchRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartMatch not implemented")
}
func (UnimplementedQuipManagerServer) CancelMatch(context.Context, *CancelMatchRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelMatch not implemented")
}
func (UnimplementedQuipManagerServer) FinishMatch(context.Context, *FinishMatchRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FinishMatch not implemented")
}

// UnsafeQuipManagerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QuipManagerServer will
// result in compilation errors.
type UnsafeQuipManagerServer interface {
	mustEmbedUnimplementedQuipManagerServer()
}

func RegisterQuipManagerServer(s grpc.ServiceRegistrar, srv QuipManagerServer) {
	s.RegisterService(&QuipManager_ServiceDesc, srv)
}

func _QuipManager_CreateMatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuipManagerServer).CreateMatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuipManager_CreateMatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuipManagerServer).CreateMatch(ctx, req.(*CreateMatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuipManager_StartMatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartMatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuipManagerServer).StartMatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuipManager_StartMatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuipManagerServer).StartMatch(ctx, req.(*StartMatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuipManager_CancelMatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelMatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuipManagerServer).CancelMatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuipManager_CancelMatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuipManagerServer).CancelMatch(ctx, req.(*CancelMatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuipManager_FinishMatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FinishMatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuipManagerServer).FinishMatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuipManager_FinishMatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuipManagerServer).FinishMatch(ctx, req.(*FinishMatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// QuipManager_ServiceDesc is the grpc.ServiceDesc for QuipManager service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var QuipManager_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "quip.matchmaker.QuipManager",
	HandlerType: (*QuipManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateMatch",
			Handler:    _QuipManager_CreateMatch_Handler,
		},
		{
			MethodName: "StartMatch",
			Handler:    _QuipManager_StartMatch_Handler,
		},
		{
			MethodName: "CancelMatch",
			Handler:    _QuipManager_CancelMatch_Handler,
		},
		{
			MethodName: "FinishMatch",
			Handler:    _QuipManager_FinishMatch_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "matchmaker/manager.proto",
}
