// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.29.1
// 	protoc        v3.21.12
// source: matchmaker/messages.proto

package matchmaker

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlayerState int32

const (
	PlayerState_PLAYER_STATE_OFFLINE   PlayerState = 0
	PlayerState_PLAYER_STATE_ONLINE    PlayerState = 1
	PlayerState_PLAYER_STATE_IDLE      PlayerState = 2
	PlayerState_PLAYER_STATE_SEARCHING PlayerState = 3
	PlayerState_PLAYER_STATE_PLAYING   PlayerState = 4
)

// Enum value maps for PlayerState.
var (
	PlayerState_name = map[int32]string{
		0: "PLAYER_STATE_OFFLINE",
		1: "PLAYER_STATE_ONLINE",
		2: "PLAYER_STATE_IDLE",
		3: "PLAYER_STATE_SEARCHING",
		4: "PLAYER_STATE_PLAYING",
	}
	PlayerState_value = map[string]int32{
		"PLAYER_STATE_OFFLINE":   0,
		"PLAYER_STATE_ONLINE":    1,
		"PLAYER_STATE_IDLE":      2,
		"PLAYER_STATE_SEARCHING": 3,
		"PLAYER_STATE_PLAYING":   4,
	}
)

func (x PlayerState) Enum() *PlayerState {
	p := new(PlayerState)
	*p = x
	return p
}

func (x PlayerState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PlayerState) Descriptor() protoreflect.EnumDescriptor {
	return file_matchmaker_messages_proto_enumTypes[0].Descriptor()
}

func (PlayerState) Type() protoreflect.EnumType {
	return &file_matchmaker_messages_proto_enumTypes[0]
}

func (x PlayerState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PlayerState.Descriptor instead.
func (PlayerState) EnumDescriptor() ([]byte, []int) {
	return file_matchmaker_messages_proto_rawDescGZIP(), []int{0}
}

type Reason int32

const (
	Reason_REASON_UNSPECIFIED Reason = 0
	Reason_REASON_PLAYER      Reason = 1
)

// Enum value maps for Reason.
var (
	Reason_name = map[int32]string{
		0: "REASON_UNSPECIFIED",
		1: "REASON_PLAYER",
	}
	Reason_value = map[string]int32{
		"REASON_UNSPECIFIED": 0,
		"REASON_PLAYER":      1,
	}
)

func (x Reason) Enum() *Reason {
	p := new(Reason)
	*p = x
	return p
}

func (x Reason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Reason) Descriptor() protoreflect.EnumDescriptor {
	return file_matchmaker_messages_proto_enumTypes[1].Descriptor()
}

func (Reason) Type() protoreflect.EnumType {
	return &file_matchmaker_messages_proto_enumTypes[1]
}

func (x Reason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Reason.Descriptor instead.
func (Reason) EnumDescriptor() ([]byte, []int) {
	return file_matchmaker_messages_proto_rawDescGZIP(), []int{1}
}

type Player struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Id represents the player identifier.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// State is a simple enum representing whether the player is currently
	// online, idle, in queue, or in a game.
	State PlayerState `protobuf:"varint,2,opt,name=state,proto3,enum=quip.matchmaker.PlayerState" json:"state,omitempty"`
	// Assignment represents a queue or match the player is currently in.
	//
	// Types that are assignable to Assignment:
	//
	//	*Player_QueueAssignment
	//	*Player_MatchAssignment
	Assignment isPlayer_Assignment `protobuf_oneof:"assignment"`
}

func (x *Player) Reset() {
	*x = Player{}
	if protoimpl.UnsafeEnabled {
		mi := &file_matchmaker_messages_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Player) ProtoMessage() {}

func (x *Player) ProtoReflect() protoreflect.Message {
	mi := &file_matchmaker_messages_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Player.ProtoReflect.Descriptor instead.
func (*Player) Descriptor() ([]byte, []int) {
	return file_matchmaker_messages_proto_rawDescGZIP(), []int{0}
}

func (x *Player) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Player) GetState() PlayerState {
	if x != nil {
		return x.State
	}
	return PlayerState_PLAYER_STATE_OFFLINE
}

func (m *Player) GetAssignment() isPlayer_Assignment {
	if m != nil {
		return m.Assignment
	}
	return nil
}

func (x *Player) GetQueueAssignment() *QueueAssignment {
	if x, ok := x.GetAssignment().(*Player_QueueAssignment); ok {
		return x.QueueAssignment
	}
	return nil
}

func (x *Player) GetMatchAssignment() *MatchAssignment {
	if x, ok := x.GetAssignment().(*Player_MatchAssignment); ok {
		return x.MatchAssignment
	}
	return nil
}

type isPlayer_Assignment interface {
	isPlayer_Assignment()
}

type Player_QueueAssignment struct {
	QueueAssignment *QueueAssignment `protobuf:"bytes,3,opt,name=queue_assignment,json=queueAssignment,proto3,oneof"`
}

type Player_MatchAssignment struct {
	MatchAssignment *MatchAssignment `protobuf:"bytes,4,opt,name=match_assignment,json=matchAssignment,proto3,oneof"`
}

func (*Player_QueueAssignment) isPlayer_Assignment() {}

func (*Player_MatchAssignment) isPlayer_Assignment() {}

type QueueAssignment struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Queue identifier to determine which queue has updated.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Config represents information about the desired game.
	Config *QueueConfiguration `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	// Start time is the time the queue began.
	StartTime *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
}

func (x *QueueAssignment) Reset() {
	*x = QueueAssignment{}
	if protoimpl.UnsafeEnabled {
		mi := &file_matchmaker_messages_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueueAssignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueAssignment) ProtoMessage() {}

func (x *QueueAssignment) ProtoReflect() protoreflect.Message {
	mi := &file_matchmaker_messages_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueAssignment.ProtoReflect.Descriptor instead.
func (*QueueAssignment) Descriptor() ([]byte, []int) {
	return file_matchmaker_messages_proto_rawDescGZIP(), []int{1}
}

func (x *QueueAssignment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *QueueAssignment) GetConfig() *QueueConfiguration {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *QueueAssignment) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

type QueueConfiguration struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Gamemode string `protobuf:"bytes,1,opt,name=gamemode,proto3" json:"gamemode,omitempty"`
}

func (x *QueueConfiguration) Reset() {
	*x = QueueConfiguration{}
	if protoimpl.UnsafeEnabled {
		mi := &file_matchmaker_messages_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueueConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueConfiguration) ProtoMessage() {}

func (x *QueueConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_matchmaker_messages_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueConfiguration.ProtoReflect.Descriptor instead.
func (*QueueConfiguration) Descriptor() ([]byte, []int) {
	return file_matchmaker_messages_proto_rawDescGZIP(), []int{2}
}

func (x *QueueConfiguration) GetGamemode() string {
	if x != nil {
		return x.Gamemode
	}
	return ""
}

type MatchAssignment struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Id represents the auto-generated match id.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Connection information for this match.
	Connection string `protobuf:"bytes,2,opt,name=connection,proto3" json:"connection,omitempty"`
}

func (x *MatchAssignment) Reset() {
	*x = MatchAssignment{}
	if protoimpl.UnsafeEnabled {
		mi := &file_matchmaker_messages_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MatchAssignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchAssignment) ProtoMessage() {}

func (x *MatchAssignment) ProtoReflect() protoreflect.Message {
	mi := &file_matchmaker_messages_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchAssignment.ProtoReflect.Descriptor instead.
func (*MatchAssignment) Descriptor() ([]byte, []int) {
	return file_matchmaker_messages_proto_rawDescGZIP(), []int{3}
}

func (x *MatchAssignment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MatchAssignment) GetConnection() string {
	if x != nil {
		return x.Connection
	}
	return ""
}

type StatusUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Update:
	//
	//	*StatusUpdate_QueueStarted
	//	*StatusUpdate_QueueStopped
	//	*StatusUpdate_MatchFound
	//	*StatusUpdate_MatchCancelled
	//	*StatusUpdate_MatchStarted
	//	*StatusUpdate_MatchFinished
	Update isStatusUpdate_Update `protobuf_oneof:"update"`
}

func (x *StatusUpdate) Reset() {
	*x = StatusUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_matchmaker_messages_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatusUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusUpdate) ProtoMessage() {}

func (x *StatusUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_matchmaker_messages_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusUpdate.ProtoReflect.Descriptor instead.
func (*StatusUpdate) Descriptor() ([]byte, []int) {
	return file_matchmaker_messages_proto_rawDescGZIP(), []int{4}
}

func (m *StatusUpdate) GetUpdate() isStatusUpdate_Update {
	if m != nil {
		return m.Update
	}
	return nil
}

func (x *StatusUpdate) GetQueueStarted() *QueueAssignment {
	if x, ok := x.GetUpdate().(*StatusUpdate_QueueStarted); ok {
		return x.QueueStarted
	}
	return nil
}

func (x *StatusUpdate) GetQueueStopped() *QueueStopped {
	if x, ok := x.GetUpdate().(*StatusUpdate_QueueStopped); ok {
		return x.QueueStopped
	}
	return nil
}

func (x *StatusUpdate) GetMatchFound() *MatchFound {
	if x, ok := x.GetUpdate().(*StatusUpdate_MatchFound); ok {
		return x.MatchFound
	}
	return nil
}

func (x *StatusUpdate) GetMatchCancelled() *MatchCancelled {
	if x, ok := x.GetUpdate().(*StatusUpdate_MatchCancelled); ok {
		return x.MatchCancelled
	}
	return nil
}

func (x *StatusUpdate) GetMatchStarted() *MatchStarted {
	if x, ok := x.GetUpdate().(*StatusUpdate_MatchStarted); ok {
		return x.MatchStarted
	}
	return nil
}

func (x *StatusUpdate) GetMatchFinished() *MatchFinished {
	if x, ok := x.GetUpdate().(*StatusUpdate_MatchFinished); ok {
		return x.MatchFinished
	}
	return nil
}

type isStatusUpdate_Update interface {
	isStatusUpdate_Update()
}

type StatusUpdate_QueueStarted struct {
	QueueStarted *QueueAssignment `protobuf:"bytes,2,opt,name=queue_started,json=queueStarted,proto3,oneof"`
}

type StatusUpdate_QueueStopped struct {
	QueueStopped *QueueStopped `protobuf:"bytes,3,opt,name=queue_stopped,json=queueStopped,proto3,oneof"`
}

type StatusUpdate_MatchFound struct {
	MatchFound *MatchFound `protobuf:"bytes,4,opt,name=match_found,json=matchFound,proto3,oneof"`
}

type StatusUpdate_MatchCancelled struct {
	MatchCancelled *MatchCancelled `protobuf:"bytes,5,opt,name=match_cancelled,json=matchCancelled,proto3,oneof"`
}

type StatusUpdate_MatchStarted struct {
	MatchStarted *MatchStarted `protobuf:"bytes,6,opt,name=match_started,json=matchStarted,proto3,oneof"`
}

type StatusUpdate_MatchFinished struct {
	MatchFinished *MatchFinished `protobuf:"bytes,7,opt,name=match_finished,json=matchFinished,proto3,oneof"`
}

func (*StatusUpdate_QueueStarted) isStatusUpdate_Update() {}

func (*StatusUpdate_QueueStopped) isStatusUpdate_Update() {}

func (*StatusUpdate_MatchFound) isStatusUpdate_Update() {}

func (*StatusUpdate_MatchCancelled) isStatusUpdate_Update() {}

func (*StatusUpdate_MatchStarted) isStatusUpdate_Update() {}

func (*StatusUpdate_MatchFinished) isStatusUpdate_Update() {}

// QueueStopped contains information about why a queue has stopped.
type QueueStopped struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Reason  Reason  `protobuf:"varint,2,opt,name=reason,proto3,enum=quip.matchmaker.Reason" json:"reason,omitempty"`
	Message *string `protobuf:"bytes,3,opt,name=message,proto3,oneof" json:"message,omitempty"`
}

func (x *QueueStopped) Reset() {
	*x = QueueStopped{}
	if protoimpl.UnsafeEnabled {
		mi := &file_matchmaker_messages_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueueStopped) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueStopped) ProtoMessage() {}

func (x *QueueStopped) ProtoReflect() protoreflect.Message {
	mi := &file_matchmaker_messages_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueStopped.ProtoReflect.Descriptor instead.
func (*QueueStopped) Descriptor() ([]byte, []int) {
	return file_matchmaker_messages_proto_rawDescGZIP(), []int{5}
}

func (x *QueueStopped) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *QueueStopped) GetReason() Reason {
	if x != nil {
		return x.Reason
	}
	return Reason_REASON_UNSPECIFIED
}

func (x *QueueStopped) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

// MatchFound contains information about a potential match that was found.
// Sent as intermediate step for players to accept (send match wager) match before
// allocating a server.
type MatchFound struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MatchId string                 `protobuf:"bytes,1,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	Time    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
}

func (x *MatchFound) Reset() {
	*x = MatchFound{}
	if protoimpl.UnsafeEnabled {
		mi := &file_matchmaker_messages_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MatchFound) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchFound) ProtoMessage() {}

func (x *MatchFound) ProtoReflect() protoreflect.Message {
	mi := &file_matchmaker_messages_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchFound.ProtoReflect.Descriptor instead.
func (*MatchFound) Descriptor() ([]byte, []int) {
	return file_matchmaker_messages_proto_rawDescGZIP(), []int{6}
}

func (x *MatchFound) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

func (x *MatchFound) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

type MatchCancelled struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MatchId string `protobuf:"bytes,1,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	Reason  Reason `protobuf:"varint,2,opt,name=reason,proto3,enum=quip.matchmaker.Reason" json:"reason,omitempty"`
}

func (x *MatchCancelled) Reset() {
	*x = MatchCancelled{}
	if protoimpl.UnsafeEnabled {
		mi := &file_matchmaker_messages_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MatchCancelled) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchCancelled) ProtoMessage() {}

func (x *MatchCancelled) ProtoReflect() protoreflect.Message {
	mi := &file_matchmaker_messages_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchCancelled.ProtoReflect.Descriptor instead.
func (*MatchCancelled) Descriptor() ([]byte, []int) {
	return file_matchmaker_messages_proto_rawDescGZIP(), []int{7}
}

func (x *MatchCancelled) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

func (x *MatchCancelled) GetReason() Reason {
	if x != nil {
		return x.Reason
	}
	return Reason_REASON_UNSPECIFIED
}

// MatchStarted contains necessary match information to identify and connect to a match.
type MatchStarted struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MatchId    string `protobuf:"bytes,1,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	Connection string `protobuf:"bytes,2,opt,name=connection,proto3" json:"connection,omitempty"`
}

func (x *MatchStarted) Reset() {
	*x = MatchStarted{}
	if protoimpl.UnsafeEnabled {
		mi := &file_matchmaker_messages_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MatchStarted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchStarted) ProtoMessage() {}

func (x *MatchStarted) ProtoReflect() protoreflect.Message {
	mi := &file_matchmaker_messages_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchStarted.ProtoReflect.Descriptor instead.
func (*MatchStarted) Descriptor() ([]byte, []int) {
	return file_matchmaker_messages_proto_rawDescGZIP(), []int{8}
}

func (x *MatchStarted) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

func (x *MatchStarted) GetConnection() string {
	if x != nil {
		return x.Connection
	}
	return ""
}

type MatchFinished struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MatchId string `protobuf:"bytes,1,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
}

func (x *MatchFinished) Reset() {
	*x = MatchFinished{}
	if protoimpl.UnsafeEnabled {
		mi := &file_matchmaker_messages_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MatchFinished) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchFinished) ProtoMessage() {}

func (x *MatchFinished) ProtoReflect() protoreflect.Message {
	mi := &file_matchmaker_messages_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchFinished.ProtoReflect.Descriptor instead.
func (*MatchFinished) Descriptor() ([]byte, []int) {
	return file_matchmaker_messages_proto_rawDescGZIP(), []int{9}
}

func (x *MatchFinished) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

type MatchConfiguration struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Gamemode string `protobuf:"bytes,1,opt,name=gamemode,proto3" json:"gamemode,omitempty"`
}

func (x *MatchConfiguration) Reset() {
	*x = MatchConfiguration{}
	if protoimpl.UnsafeEnabled {
		mi := &file_matchmaker_messages_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MatchConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchConfiguration) ProtoMessage() {}

func (x *MatchConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_matchmaker_messages_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchConfiguration.ProtoReflect.Descriptor instead.
func (*MatchConfiguration) Descriptor() ([]byte, []int) {
	return file_matchmaker_messages_proto_rawDescGZIP(), []int{10}
}

func (x *MatchConfiguration) GetGamemode() string {
	if x != nil {
		return x.Gamemode
	}
	return ""
}

// MatchRoster contains necessary information for a gameserver to setup.
type MatchRoster struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Players []string `protobuf:"bytes,1,rep,name=players,proto3" json:"players,omitempty"`
}

func (x *MatchRoster) Reset() {
	*x = MatchRoster{}
	if protoimpl.UnsafeEnabled {
		mi := &file_matchmaker_messages_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MatchRoster) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchRoster) ProtoMessage() {}

func (x *MatchRoster) ProtoReflect() protoreflect.Message {
	mi := &file_matchmaker_messages_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchRoster.ProtoReflect.Descriptor instead.
func (*MatchRoster) Descriptor() ([]byte, []int) {
	return file_matchmaker_messages_proto_rawDescGZIP(), []int{11}
}

func (x *MatchRoster) GetPlayers() []string {
	if x != nil {
		return x.Players
	}
	return nil
}

type MatchResults struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MatchResults) Reset() {
	*x = MatchResults{}
	if protoimpl.UnsafeEnabled {
		mi := &file_matchmaker_messages_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MatchResults) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchResults) ProtoMessage() {}

func (x *MatchResults) ProtoReflect() protoreflect.Message {
	mi := &file_matchmaker_messages_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchResults.ProtoReflect.Descriptor instead.
func (*MatchResults) Descriptor() ([]byte, []int) {
	return file_matchmaker_messages_proto_rawDescGZIP(), []int{12}
}

var File_matchmaker_messages_proto protoreflect.FileDescriptor

var file_matchmaker_messages_proto_rawDesc = []byte{
	0x0a, 0x19, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x6d, 0x61, 0x6b, 0x65, 0x72, 0x2f, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x71, 0x75, 0x69,
	0x70, 0x2e, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x6d, 0x61, 0x6b, 0x65, 0x72, 0x1a, 0x1f, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xf8, 0x01,
	0x0a, 0x06, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x32, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x71, 0x75, 0x69, 0x70, 0x2e, 0x6d,
	0x61, 0x74, 0x63, 0x68, 0x6d, 0x61, 0x6b, 0x65, 0x72, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x4d, 0x0a, 0x10,
	0x71, 0x75, 0x65, 0x75, 0x65, 0x5f, 0x61, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x6d, 0x65, 0x6e, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x71, 0x75, 0x69, 0x70, 0x2e, 0x6d, 0x61,
	0x74, 0x63, 0x68, 0x6d, 0x61, 0x6b, 0x65, 0x72, 0x2e, 0x51, 0x75, 0x65, 0x75, 0x65, 0x41, 0x73,
	0x73, 0x69, 0x67, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x0f, 0x71, 0x75, 0x65, 0x75,
	0x65, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x4d, 0x0a, 0x10, 0x6d,
	0x61, 0x74, 0x63, 0x68, 0x5f, 0x61, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x71, 0x75, 0x69, 0x70, 0x2e, 0x6d, 0x61, 0x74,
	0x63, 0x68, 0x6d, 0x61, 0x6b, 0x65, 0x72, 0x2e, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x41, 0x73, 0x73,
	0x69, 0x67, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x0f, 0x6d, 0x61, 0x74, 0x63, 0x68,
	0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x42, 0x0c, 0x0a, 0x0a, 0x61, 0x73,
	0x73, 0x69, 0x67, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0x99, 0x01, 0x0a, 0x0f, 0x51, 0x75, 0x65,
	0x75, 0x65, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x3b, 0x0a, 0x06,
	0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x71,
	0x75, 0x69, 0x70, 0x2e, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x6d, 0x61, 0x6b, 0x65, 0x72, 0x2e, 0x51,
	0x75, 0x65, 0x75, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x39, 0x0a, 0x0a, 0x73, 0x74, 0x61,
	0x72, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74,
	0x54, 0x69, 0x6d, 0x65, 0x22, 0x30, 0x0a, 0x12, 0x51, 0x75, 0x65, 0x75, 0x65, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x67, 0x61,
	0x6d, 0x65, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x67, 0x61,
	0x6d, 0x65, 0x6d, 0x6f, 0x64, 0x65, 0x22, 0x41, 0x0a, 0x0f, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x41,
	0x73, 0x73, 0x69, 0x67, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x6f, 0x6e,
	0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63,
	0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0xc2, 0x03, 0x0a, 0x0c, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x47, 0x0a, 0x0d, 0x71, 0x75,
	0x65, 0x75, 0x65, 0x5f, 0x73, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x20, 0x2e, 0x71, 0x75, 0x69, 0x70, 0x2e, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x6d, 0x61,
	0x6b, 0x65, 0x72, 0x2e, 0x51, 0x75, 0x65, 0x75, 0x65, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x6d,
	0x65, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x0c, 0x71, 0x75, 0x65, 0x75, 0x65, 0x53, 0x74, 0x61, 0x72,
	0x74, 0x65, 0x64, 0x12, 0x44, 0x0a, 0x0d, 0x71, 0x75, 0x65, 0x75, 0x65, 0x5f, 0x73, 0x74, 0x6f,
	0x70, 0x70, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x71, 0x75, 0x69,
	0x70, 0x2e, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x6d, 0x61, 0x6b, 0x65, 0x72, 0x2e, 0x51, 0x75, 0x65,
	0x75, 0x65, 0x53, 0x74, 0x6f, 0x70, 0x70, 0x65, 0x64, 0x48, 0x00, 0x52, 0x0c, 0x71, 0x75, 0x65,
	0x75, 0x65, 0x53, 0x74, 0x6f, 0x70, 0x70, 0x65, 0x64, 0x12, 0x3e, 0x0a, 0x0b, 0x6d, 0x61, 0x74,
	0x63, 0x68, 0x5f, 0x66, 0x6f, 0x75, 0x6e, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b,
	0x2e, 0x71, 0x75, 0x69, 0x70, 0x2e, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x6d, 0x61, 0x6b, 0x65, 0x72,
	0x2e, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x46, 0x6f, 0x75, 0x6e, 0x64, 0x48, 0x00, 0x52, 0x0a, 0x6d,
	0x61, 0x74, 0x63, 0x68, 0x46, 0x6f, 0x75, 0x6e, 0x64, 0x12, 0x4a, 0x0a, 0x0f, 0x6d, 0x61, 0x74,
	0x63, 0x68, 0x5f, 0x63, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x6c, 0x65, 0x64, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x71, 0x75, 0x69, 0x70, 0x2e, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x6d,
	0x61, 0x6b, 0x65, 0x72, 0x2e, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c,
	0x6c, 0x65, 0x64, 0x48, 0x00, 0x52, 0x0e, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x43, 0x61, 0x6e, 0x63,
	0x65, 0x6c, 0x6c, 0x65, 0x64, 0x12, 0x44, 0x0a, 0x0d, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x73,
	0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x71,
	0x75, 0x69, 0x70, 0x2e, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x6d, 0x61, 0x6b, 0x65, 0x72, 0x2e, 0x4d,
	0x61, 0x74, 0x63, 0x68, 0x53, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x48, 0x00, 0x52, 0x0c, 0x6d,
	0x61, 0x74, 0x63, 0x68, 0x53, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x12, 0x47, 0x0a, 0x0e, 0x6d,
	0x61, 0x74, 0x63, 0x68, 0x5f, 0x66, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x65, 0x64, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x71, 0x75, 0x69, 0x70, 0x2e, 0x6d, 0x61, 0x74, 0x63, 0x68,
	0x6d, 0x61, 0x6b, 0x65, 0x72, 0x2e, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x46, 0x69, 0x6e, 0x69, 0x73,
	0x68, 0x65, 0x64, 0x48, 0x00, 0x52, 0x0d, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x46, 0x69, 0x6e, 0x69,
	0x73, 0x68, 0x65, 0x64, 0x42, 0x08, 0x0a, 0x06, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x22, 0x7a,
	0x0a, 0x0c, 0x51, 0x75, 0x65, 0x75, 0x65, 0x53, 0x74, 0x6f, 0x70, 0x70, 0x65, 0x64, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x2f,
	0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x17,
	0x2e, 0x71, 0x75, 0x69, 0x70, 0x2e, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x6d, 0x61, 0x6b, 0x65, 0x72,
	0x2e, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12,
	0x1d, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x48, 0x00, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x88, 0x01, 0x01, 0x42, 0x0a,
	0x0a, 0x08, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x57, 0x0a, 0x0a, 0x4d, 0x61,
	0x74, 0x63, 0x68, 0x46, 0x6f, 0x75, 0x6e, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x6d, 0x61, 0x74, 0x63,
	0x68, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x61, 0x74, 0x63,
	0x68, 0x49, 0x64, 0x12, 0x2e, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x04, 0x74,
	0x69, 0x6d, 0x65, 0x22, 0x5c, 0x0a, 0x0e, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x43, 0x61, 0x6e, 0x63,
	0x65, 0x6c, 0x6c, 0x65, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x49, 0x64,
	0x12, 0x2f, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x17, 0x2e, 0x71, 0x75, 0x69, 0x70, 0x2e, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x6d, 0x61, 0x6b,
	0x65, 0x72, 0x2e, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f,
	0x6e, 0x22, 0x49, 0x0a, 0x0c, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x53, 0x74, 0x61, 0x72, 0x74, 0x65,
	0x64, 0x12, 0x19, 0x0a, 0x08, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a,
	0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x2a, 0x0a, 0x0d,
	0x4d, 0x61, 0x74, 0x63, 0x68, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x65, 0x64, 0x12, 0x19, 0x0a,
	0x08, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x49, 0x64, 0x22, 0x30, 0x0a, 0x12, 0x4d, 0x61, 0x74, 0x63,
	0x68, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a,
	0x0a, 0x08, 0x67, 0x61, 0x6d, 0x65, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x67, 0x61, 0x6d, 0x65, 0x6d, 0x6f, 0x64, 0x65, 0x22, 0x27, 0x0a, 0x0b, 0x4d, 0x61,
	0x74, 0x63, 0x68, 0x52, 0x6f, 0x73, 0x74, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x70, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x73, 0x22, 0x0e, 0x0a, 0x0c, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x73, 0x2a, 0x8d, 0x01, 0x0a, 0x0b, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x12, 0x18, 0x0a, 0x14, 0x50, 0x4c, 0x41, 0x59, 0x45, 0x52, 0x5f, 0x53, 0x54,
	0x41, 0x54, 0x45, 0x5f, 0x4f, 0x46, 0x46, 0x4c, 0x49, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x17, 0x0a,
	0x13, 0x50, 0x4c, 0x41, 0x59, 0x45, 0x52, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x4f, 0x4e,
	0x4c, 0x49, 0x4e, 0x45, 0x10, 0x01, 0x12, 0x15, 0x0a, 0x11, 0x50, 0x4c, 0x41, 0x59, 0x45, 0x52,
	0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x49, 0x44, 0x4c, 0x45, 0x10, 0x02, 0x12, 0x1a, 0x0a,
	0x16, 0x50, 0x4c, 0x41, 0x59, 0x45, 0x52, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x53, 0x45,
	0x41, 0x52, 0x43, 0x48, 0x49, 0x4e, 0x47, 0x10, 0x03, 0x12, 0x18, 0x0a, 0x14, 0x50, 0x4c, 0x41,
	0x59, 0x45, 0x52, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x50, 0x4c, 0x41, 0x59, 0x49, 0x4e,
	0x47, 0x10, 0x04, 0x2a, 0x33, 0x0a, 0x06, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x16, 0x0a,
	0x12, 0x52, 0x45, 0x41, 0x53, 0x4f, 0x4e, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46,
	0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x11, 0x0a, 0x0d, 0x52, 0x45, 0x41, 0x53, 0x4f, 0x4e, 0x5f,
	0x50, 0x4c, 0x41, 0x59, 0x45, 0x52, 0x10, 0x01, 0x42, 0x2e, 0x5a, 0x2c, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x47, 0x61, 0x6d, 0x62, 0x69, 0x74, 0x4c, 0x4c, 0x43,
	0x2f, 0x71, 0x75, 0x69, 0x70, 0x2f, 0x6c, 0x69, 0x62, 0x73, 0x2f, 0x70, 0x62, 0x2f, 0x6d, 0x61,
	0x74, 0x63, 0x68, 0x6d, 0x61, 0x6b, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_matchmaker_messages_proto_rawDescOnce sync.Once
	file_matchmaker_messages_proto_rawDescData = file_matchmaker_messages_proto_rawDesc
)

func file_matchmaker_messages_proto_rawDescGZIP() []byte {
	file_matchmaker_messages_proto_rawDescOnce.Do(func() {
		file_matchmaker_messages_proto_rawDescData = protoimpl.X.CompressGZIP(file_matchmaker_messages_proto_rawDescData)
	})
	return file_matchmaker_messages_proto_rawDescData
}

var file_matchmaker_messages_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_matchmaker_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_matchmaker_messages_proto_goTypes = []interface{}{
	(PlayerState)(0),              // 0: quip.matchmaker.PlayerState
	(Reason)(0),                   // 1: quip.matchmaker.Reason
	(*Player)(nil),                // 2: quip.matchmaker.Player
	(*QueueAssignment)(nil),       // 3: quip.matchmaker.QueueAssignment
	(*QueueConfiguration)(nil),    // 4: quip.matchmaker.QueueConfiguration
	(*MatchAssignment)(nil),       // 5: quip.matchmaker.MatchAssignment
	(*StatusUpdate)(nil),          // 6: quip.matchmaker.StatusUpdate
	(*QueueStopped)(nil),          // 7: quip.matchmaker.QueueStopped
	(*MatchFound)(nil),            // 8: quip.matchmaker.MatchFound
	(*MatchCancelled)(nil),        // 9: quip.matchmaker.MatchCancelled
	(*MatchStarted)(nil),          // 10: quip.matchmaker.MatchStarted
	(*MatchFinished)(nil),         // 11: quip.matchmaker.MatchFinished
	(*MatchConfiguration)(nil),    // 12: quip.matchmaker.MatchConfiguration
	(*MatchRoster)(nil),           // 13: quip.matchmaker.MatchRoster
	(*MatchResults)(nil),          // 14: quip.matchmaker.MatchResults
	(*timestamppb.Timestamp)(nil), // 15: google.protobuf.Timestamp
}
var file_matchmaker_messages_proto_depIdxs = []int32{
	0,  // 0: quip.matchmaker.Player.state:type_name -> quip.matchmaker.PlayerState
	3,  // 1: quip.matchmaker.Player.queue_assignment:type_name -> quip.matchmaker.QueueAssignment
	5,  // 2: quip.matchmaker.Player.match_assignment:type_name -> quip.matchmaker.MatchAssignment
	4,  // 3: quip.matchmaker.QueueAssignment.config:type_name -> quip.matchmaker.QueueConfiguration
	15, // 4: quip.matchmaker.QueueAssignment.start_time:type_name -> google.protobuf.Timestamp
	3,  // 5: quip.matchmaker.StatusUpdate.queue_started:type_name -> quip.matchmaker.QueueAssignment
	7,  // 6: quip.matchmaker.StatusUpdate.queue_stopped:type_name -> quip.matchmaker.QueueStopped
	8,  // 7: quip.matchmaker.StatusUpdate.match_found:type_name -> quip.matchmaker.MatchFound
	9,  // 8: quip.matchmaker.StatusUpdate.match_cancelled:type_name -> quip.matchmaker.MatchCancelled
	10, // 9: quip.matchmaker.StatusUpdate.match_started:type_name -> quip.matchmaker.MatchStarted
	11, // 10: quip.matchmaker.StatusUpdate.match_finished:type_name -> quip.matchmaker.MatchFinished
	1,  // 11: quip.matchmaker.QueueStopped.reason:type_name -> quip.matchmaker.Reason
	15, // 12: quip.matchmaker.MatchFound.time:type_name -> google.protobuf.Timestamp
	1,  // 13: quip.matchmaker.MatchCancelled.reason:type_name -> quip.matchmaker.Reason
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_matchmaker_messages_proto_init() }
func file_matchmaker_messages_proto_init() {
	if File_matchmaker_messages_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_matchmaker_messages_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Player); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_matchmaker_messages_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueueAssignment); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_matchmaker_messages_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueueConfiguration); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_matchmaker_messages_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MatchAssignment); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_matchmaker_messages_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatusUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_matchmaker_messages_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueueStopped); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_matchmaker_messages_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MatchFound); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_matchmaker_messages_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MatchCancelled); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_matchmaker_messages_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MatchStarted); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_matchmaker_messages_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MatchFinished); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_matchmaker_messages_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MatchConfiguration); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_matchmaker_messages_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MatchRoster); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_matchmaker_messages_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MatchResults); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_matchmaker_messages_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*Player_QueueAssignment)(nil),
		(*Player_MatchAssignment)(nil),
	}
	file_matchmaker_messages_proto_msgTypes[4].OneofWrappers = []interface{}{
		(*StatusUpdate_QueueStarted)(nil),
		(*StatusUpdate_QueueStopped)(nil),
		(*StatusUpdate_MatchFound)(nil),
		(*StatusUpdate_MatchCancelled)(nil),
		(*StatusUpdate_MatchStarted)(nil),
		(*StatusUpdate_MatchFinished)(nil),
	}
	file_matchmaker_messages_proto_msgTypes[5].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_matchmaker_messages_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_matchmaker_messages_proto_goTypes,
		DependencyIndexes: file_matchmaker_messages_proto_depIdxs,
		EnumInfos:         file_matchmaker_messages_proto_enumTypes,
		MessageInfos:      file_matchmaker_messages_proto_msgTypes,
	}.Build()
	File_matchmaker_messages_proto = out.File
	file_matchmaker_messages_proto_rawDesc = nil
	file_matchmaker_messages_proto_goTypes = nil
	file_matchmaker_messages_proto_depIdxs = nil
}
