// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: matchmaker/broker.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// End user notification message. Needs to be sent as a message
// for notifying other friends or other party members.
type StateUpdateMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Targets []string    `protobuf:"bytes,1,rep,name=targets,proto3" json:"targets,omitempty"`
	State   PlayerState `protobuf:"varint,2,opt,name=state,proto3,enum=quip.matchmaker.PlayerState" json:"state,omitempty"`
}

func (x *StateUpdateMessage) Reset() {
	*x = StateUpdateMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_matchmaker_broker_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StateUpdateMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateUpdateMessage) ProtoMessage() {}

func (x *StateUpdateMessage) ProtoReflect() protoreflect.Message {
	mi := &file_matchmaker_broker_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateUpdateMessage.ProtoReflect.Descriptor instead.
func (*StateUpdateMessage) Descriptor() ([]byte, []int) {
	return file_matchmaker_broker_proto_rawDescGZIP(), []int{0}
}

func (x *StateUpdateMessage) GetTargets() []string {
	if x != nil {
		return x.Targets
	}
	return nil
}

func (x *StateUpdateMessage) GetState() PlayerState {
	if x != nil {
		return x.State
	}
	return PlayerState_PLAYER_STATE_OFFLINE
}

// End user notification message. Needs to be sent as a message
// for notifying other friends or other party members.
type StatusUpdateMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Targets []string      `protobuf:"bytes,1,rep,name=targets,proto3" json:"targets,omitempty"`
	Update  *StatusUpdate `protobuf:"bytes,2,opt,name=update,proto3" json:"update,omitempty"`
}

func (x *StatusUpdateMessage) Reset() {
	*x = StatusUpdateMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_matchmaker_broker_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatusUpdateMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusUpdateMessage) ProtoMessage() {}

func (x *StatusUpdateMessage) ProtoReflect() protoreflect.Message {
	mi := &file_matchmaker_broker_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusUpdateMessage.ProtoReflect.Descriptor instead.
func (*StatusUpdateMessage) Descriptor() ([]byte, []int) {
	return file_matchmaker_broker_proto_rawDescGZIP(), []int{1}
}

func (x *StatusUpdateMessage) GetTargets() []string {
	if x != nil {
		return x.Targets
	}
	return nil
}

func (x *StatusUpdateMessage) GetUpdate() *StatusUpdate {
	if x != nil {
		return x.Update
	}
	return nil
}

// Internal broker message. Mainly sent by director or gameservers.
// TODO: this may not be necessary? can possibly watch solana transactions
type MatchUpdateMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Update:
	//
	//	*MatchUpdateMessage_MatchCancelled
	//	*MatchUpdateMessage_MatchStarted
	//	*MatchUpdateMessage_MatchFinished
	Update isMatchUpdateMessage_Update `protobuf_oneof:"update"`
}

func (x *MatchUpdateMessage) Reset() {
	*x = MatchUpdateMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_matchmaker_broker_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MatchUpdateMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchUpdateMessage) ProtoMessage() {}

func (x *MatchUpdateMessage) ProtoReflect() protoreflect.Message {
	mi := &file_matchmaker_broker_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchUpdateMessage.ProtoReflect.Descriptor instead.
func (*MatchUpdateMessage) Descriptor() ([]byte, []int) {
	return file_matchmaker_broker_proto_rawDescGZIP(), []int{2}
}

func (m *MatchUpdateMessage) GetUpdate() isMatchUpdateMessage_Update {
	if m != nil {
		return m.Update
	}
	return nil
}

func (x *MatchUpdateMessage) GetMatchCancelled() *MatchCancelled {
	if x, ok := x.GetUpdate().(*MatchUpdateMessage_MatchCancelled); ok {
		return x.MatchCancelled
	}
	return nil
}

func (x *MatchUpdateMessage) GetMatchStarted() *MatchStarted {
	if x, ok := x.GetUpdate().(*MatchUpdateMessage_MatchStarted); ok {
		return x.MatchStarted
	}
	return nil
}

func (x *MatchUpdateMessage) GetMatchFinished() *MatchResults {
	if x, ok := x.GetUpdate().(*MatchUpdateMessage_MatchFinished); ok {
		return x.MatchFinished
	}
	return nil
}

type isMatchUpdateMessage_Update interface {
	isMatchUpdateMessage_Update()
}

type MatchUpdateMessage_MatchCancelled struct {
	MatchCancelled *MatchCancelled `protobuf:"bytes,1,opt,name=match_cancelled,json=matchCancelled,proto3,oneof"`
}

type MatchUpdateMessage_MatchStarted struct {
	MatchStarted *MatchStarted `protobuf:"bytes,2,opt,name=match_started,json=matchStarted,proto3,oneof"`
}

type MatchUpdateMessage_MatchFinished struct {
	MatchFinished *MatchResults `protobuf:"bytes,3,opt,name=match_finished,json=matchFinished,proto3,oneof"`
}

func (*MatchUpdateMessage_MatchCancelled) isMatchUpdateMessage_Update() {}

func (*MatchUpdateMessage_MatchStarted) isMatchUpdateMessage_Update() {}

func (*MatchUpdateMessage_MatchFinished) isMatchUpdateMessage_Update() {}

var File_matchmaker_broker_proto protoreflect.FileDescriptor

var file_matchmaker_broker_proto_rawDesc = []byte{
	0x0a, 0x17, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x6d, 0x61, 0x6b, 0x65, 0x72, 0x2f, 0x62, 0x72, 0x6f,
	0x6b, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x71, 0x75, 0x69, 0x70, 0x2e,
	0x6d, 0x61, 0x74, 0x63, 0x68, 0x6d, 0x61, 0x6b, 0x65, 0x72, 0x1a, 0x19, 0x6d, 0x61, 0x74, 0x63,
	0x68, 0x6d, 0x61, 0x6b, 0x65, 0x72, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x62, 0x0a, 0x12, 0x53, 0x74, 0x61, 0x74, 0x65, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x74,
	0x61, 0x72, 0x67, 0x65, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x74, 0x61,
	0x72, 0x67, 0x65, 0x74, 0x73, 0x12, 0x32, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x71, 0x75, 0x69, 0x70, 0x2e, 0x6d, 0x61, 0x74, 0x63,
	0x68, 0x6d, 0x61, 0x6b, 0x65, 0x72, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x22, 0x66, 0x0a, 0x13, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x07, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x73, 0x12, 0x35, 0x0a, 0x06, 0x75, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x71, 0x75, 0x69,
	0x70, 0x2e, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x6d, 0x61, 0x6b, 0x65, 0x72, 0x2e, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x06, 0x75, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x22, 0xf8, 0x01, 0x0a, 0x12, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x4a, 0x0a, 0x0f, 0x6d, 0x61, 0x74, 0x63,
	0x68, 0x5f, 0x63, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x6c, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1f, 0x2e, 0x71, 0x75, 0x69, 0x70, 0x2e, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x6d, 0x61,
	0x6b, 0x65, 0x72, 0x2e, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x6c,
	0x65, 0x64, 0x48, 0x00, 0x52, 0x0e, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x43, 0x61, 0x6e, 0x63, 0x65,
	0x6c, 0x6c, 0x65, 0x64, 0x12, 0x44, 0x0a, 0x0d, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x73, 0x74,
	0x61, 0x72, 0x74, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x71, 0x75,
	0x69, 0x70, 0x2e, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x6d, 0x61, 0x6b, 0x65, 0x72, 0x2e, 0x4d, 0x61,
	0x74, 0x63, 0x68, 0x53, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x48, 0x00, 0x52, 0x0c, 0x6d, 0x61,
	0x74, 0x63, 0x68, 0x53, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x12, 0x46, 0x0a, 0x0e, 0x6d, 0x61,
	0x74, 0x63, 0x68, 0x5f, 0x66, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x71, 0x75, 0x69, 0x70, 0x2e, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x6d,
	0x61, 0x6b, 0x65, 0x72, 0x2e, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x73, 0x48, 0x00, 0x52, 0x0d, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68,
	0x65, 0x64, 0x42, 0x08, 0x0a, 0x06, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x2d, 0x5a, 0x2b,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x47, 0x61, 0x6d, 0x62, 0x69,
	0x74, 0x4c, 0x4c, 0x43, 0x2f, 0x71, 0x75, 0x69, 0x70, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x6d, 0x61,
	0x74, 0x63, 0x68, 0x6d, 0x61, 0x6b, 0x65, 0x72, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_matchmaker_broker_proto_rawDescOnce sync.Once
	file_matchmaker_broker_proto_rawDescData = file_matchmaker_broker_proto_rawDesc
)

func file_matchmaker_broker_proto_rawDescGZIP() []byte {
	file_matchmaker_broker_proto_rawDescOnce.Do(func() {
		file_matchmaker_broker_proto_rawDescData = protoimpl.X.CompressGZIP(file_matchmaker_broker_proto_rawDescData)
	})
	return file_matchmaker_broker_proto_rawDescData
}

var file_matchmaker_broker_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_matchmaker_broker_proto_goTypes = []interface{}{
	(*StateUpdateMessage)(nil),  // 0: quip.matchmaker.StateUpdateMessage
	(*StatusUpdateMessage)(nil), // 1: quip.matchmaker.StatusUpdateMessage
	(*MatchUpdateMessage)(nil),  // 2: quip.matchmaker.MatchUpdateMessage
	(PlayerState)(0),            // 3: quip.matchmaker.PlayerState
	(*StatusUpdate)(nil),        // 4: quip.matchmaker.StatusUpdate
	(*MatchCancelled)(nil),      // 5: quip.matchmaker.MatchCancelled
	(*MatchStarted)(nil),        // 6: quip.matchmaker.MatchStarted
	(*MatchResults)(nil),        // 7: quip.matchmaker.MatchResults
}
var file_matchmaker_broker_proto_depIdxs = []int32{
	3, // 0: quip.matchmaker.StateUpdateMessage.state:type_name -> quip.matchmaker.PlayerState
	4, // 1: quip.matchmaker.StatusUpdateMessage.update:type_name -> quip.matchmaker.StatusUpdate
	5, // 2: quip.matchmaker.MatchUpdateMessage.match_cancelled:type_name -> quip.matchmaker.MatchCancelled
	6, // 3: quip.matchmaker.MatchUpdateMessage.match_started:type_name -> quip.matchmaker.MatchStarted
	7, // 4: quip.matchmaker.MatchUpdateMessage.match_finished:type_name -> quip.matchmaker.MatchResults
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_matchmaker_broker_proto_init() }
func file_matchmaker_broker_proto_init() {
	if File_matchmaker_broker_proto != nil {
		return
	}
	file_matchmaker_messages_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_matchmaker_broker_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StateUpdateMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_matchmaker_broker_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatusUpdateMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_matchmaker_broker_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MatchUpdateMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_matchmaker_broker_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*MatchUpdateMessage_MatchCancelled)(nil),
		(*MatchUpdateMessage_MatchStarted)(nil),
		(*MatchUpdateMessage_MatchFinished)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_matchmaker_broker_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_matchmaker_broker_proto_goTypes,
		DependencyIndexes: file_matchmaker_broker_proto_depIdxs,
		MessageInfos:      file_matchmaker_broker_proto_msgTypes,
	}.Build()
	File_matchmaker_broker_proto = out.File
	file_matchmaker_broker_proto_rawDesc = nil
	file_matchmaker_broker_proto_goTypes = nil
	file_matchmaker_broker_proto_depIdxs = nil
}
