// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: quip-backend.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MatchState int32

const (
	MatchState_MATCH_STATE_UNSPECIFIED MatchState = 0
	MatchState_MATCH_STATE_PENDING     MatchState = 1 // Match has been allocated and is waiting for connections.
	MatchState_MATCH_STATE_PLAYING     MatchState = 2 // Match is in progress.
	MatchState_MATCH_STATE_FINISHED    MatchState = 3 // Match has completed.
)

// Enum value maps for MatchState.
var (
	MatchState_name = map[int32]string{
		0: "MATCH_STATE_UNSPECIFIED",
		1: "MATCH_STATE_PENDING",
		2: "MATCH_STATE_PLAYING",
		3: "MATCH_STATE_FINISHED",
	}
	MatchState_value = map[string]int32{
		"MATCH_STATE_UNSPECIFIED": 0,
		"MATCH_STATE_PENDING":     1,
		"MATCH_STATE_PLAYING":     2,
		"MATCH_STATE_FINISHED":    3,
	}
)

func (x MatchState) Enum() *MatchState {
	p := new(MatchState)
	*p = x
	return p
}

func (x MatchState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MatchState) Descriptor() protoreflect.EnumDescriptor {
	return file_quip_backend_proto_enumTypes[0].Descriptor()
}

func (MatchState) Type() protoreflect.EnumType {
	return &file_quip_backend_proto_enumTypes[0]
}

func (x MatchState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MatchState.Descriptor instead.
func (MatchState) EnumDescriptor() ([]byte, []int) {
	return file_quip_backend_proto_rawDescGZIP(), []int{0}
}

type UpdateMatchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    string     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	State MatchState `protobuf:"varint,2,opt,name=state,proto3,enum=quip.MatchState" json:"state,omitempty"`
}

func (x *UpdateMatchRequest) Reset() {
	*x = UpdateMatchRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quip_backend_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateMatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMatchRequest) ProtoMessage() {}

func (x *UpdateMatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quip_backend_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMatchRequest.ProtoReflect.Descriptor instead.
func (*UpdateMatchRequest) Descriptor() ([]byte, []int) {
	return file_quip_backend_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateMatchRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateMatchRequest) GetState() MatchState {
	if x != nil {
		return x.State
	}
	return MatchState_MATCH_STATE_UNSPECIFIED
}

var File_quip_backend_proto protoreflect.FileDescriptor

var file_quip_backend_proto_rawDesc = []byte{
	0x0a, 0x12, 0x71, 0x75, 0x69, 0x70, 0x2d, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x71, 0x75, 0x69, 0x70, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74,
	0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4c, 0x0a, 0x12, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x26, 0x0a,
	0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x71,
	0x75, 0x69, 0x70, 0x2e, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05,
	0x73, 0x74, 0x61, 0x74, 0x65, 0x2a, 0x75, 0x0a, 0x0a, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x12, 0x1b, 0x0a, 0x17, 0x4d, 0x41, 0x54, 0x43, 0x48, 0x5f, 0x53, 0x54, 0x41,
	0x54, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00,
	0x12, 0x17, 0x0a, 0x13, 0x4d, 0x41, 0x54, 0x43, 0x48, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f,
	0x50, 0x45, 0x4e, 0x44, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x12, 0x17, 0x0a, 0x13, 0x4d, 0x41, 0x54,
	0x43, 0x48, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x50, 0x4c, 0x41, 0x59, 0x49, 0x4e, 0x47,
	0x10, 0x02, 0x12, 0x18, 0x0a, 0x14, 0x4d, 0x41, 0x54, 0x43, 0x48, 0x5f, 0x53, 0x54, 0x41, 0x54,
	0x45, 0x5f, 0x46, 0x49, 0x4e, 0x49, 0x53, 0x48, 0x45, 0x44, 0x10, 0x03, 0x32, 0x4a, 0x0a, 0x07,
	0x42, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x12, 0x3f, 0x0a, 0x0b, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x12, 0x18, 0x2e, 0x71, 0x75, 0x69, 0x70, 0x2e, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x42, 0x23, 0x5a, 0x21, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x47, 0x61, 0x6d, 0x62, 0x69, 0x74, 0x4c, 0x4c, 0x43,
	0x2f, 0x71, 0x75, 0x69, 0x70, 0x2f, 0x6c, 0x69, 0x62, 0x73, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_quip_backend_proto_rawDescOnce sync.Once
	file_quip_backend_proto_rawDescData = file_quip_backend_proto_rawDesc
)

func file_quip_backend_proto_rawDescGZIP() []byte {
	file_quip_backend_proto_rawDescOnce.Do(func() {
		file_quip_backend_proto_rawDescData = protoimpl.X.CompressGZIP(file_quip_backend_proto_rawDescData)
	})
	return file_quip_backend_proto_rawDescData
}

var file_quip_backend_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_quip_backend_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_quip_backend_proto_goTypes = []interface{}{
	(MatchState)(0),            // 0: quip.MatchState
	(*UpdateMatchRequest)(nil), // 1: quip.UpdateMatchRequest
	(*emptypb.Empty)(nil),      // 2: google.protobuf.Empty
}
var file_quip_backend_proto_depIdxs = []int32{
	0, // 0: quip.UpdateMatchRequest.state:type_name -> quip.MatchState
	1, // 1: quip.Backend.UpdateMatch:input_type -> quip.UpdateMatchRequest
	2, // 2: quip.Backend.UpdateMatch:output_type -> google.protobuf.Empty
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_quip_backend_proto_init() }
func file_quip_backend_proto_init() {
	if File_quip_backend_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_quip_backend_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateMatchRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_quip_backend_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_quip_backend_proto_goTypes,
		DependencyIndexes: file_quip_backend_proto_depIdxs,
		EnumInfos:         file_quip_backend_proto_enumTypes,
		MessageInfos:      file_quip_backend_proto_msgTypes,
	}.Build()
	File_quip_backend_proto = out.File
	file_quip_backend_proto_rawDesc = nil
	file_quip_backend_proto_goTypes = nil
	file_quip_backend_proto_depIdxs = nil
}
