// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.29.1
// 	protoc        v3.21.12
// source: quip-messages.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_OFFLINE   Status = 0
	Status_IDLE      Status = 1
	Status_SEARCHING Status = 2
	Status_PLAYING   Status = 3
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "OFFLINE",
		1: "IDLE",
		2: "SEARCHING",
		3: "PLAYING",
	}
	Status_value = map[string]int32{
		"OFFLINE":   0,
		"IDLE":      1,
		"SEARCHING": 2,
		"PLAYING":   3,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_quip_messages_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_quip_messages_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_quip_messages_proto_rawDescGZIP(), []int{0}
}

// Indicates change in queue status.
type QueueUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Identifies the entities whose queue has received an update.
	Targets []string `protobuf:"bytes,1,rep,name=targets,proto3" json:"targets,omitempty"`
	// Types that are assignable to Update:
	//
	//	*QueueUpdate_Started
	//	*QueueUpdate_Stopped
	//	*QueueUpdate_Found
	Update isQueueUpdate_Update `protobuf_oneof:"update"`
}

func (x *QueueUpdate) Reset() {
	*x = QueueUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quip_messages_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueueUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueUpdate) ProtoMessage() {}

func (x *QueueUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_quip_messages_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueUpdate.ProtoReflect.Descriptor instead.
func (*QueueUpdate) Descriptor() ([]byte, []int) {
	return file_quip_messages_proto_rawDescGZIP(), []int{0}
}

func (x *QueueUpdate) GetTargets() []string {
	if x != nil {
		return x.Targets
	}
	return nil
}

func (m *QueueUpdate) GetUpdate() isQueueUpdate_Update {
	if m != nil {
		return m.Update
	}
	return nil
}

func (x *QueueUpdate) GetStarted() *QueueStarted {
	if x, ok := x.GetUpdate().(*QueueUpdate_Started); ok {
		return x.Started
	}
	return nil
}

func (x *QueueUpdate) GetStopped() *QueueStopped {
	if x, ok := x.GetUpdate().(*QueueUpdate_Stopped); ok {
		return x.Stopped
	}
	return nil
}

func (x *QueueUpdate) GetFound() *MatchFound {
	if x, ok := x.GetUpdate().(*QueueUpdate_Found); ok {
		return x.Found
	}
	return nil
}

type isQueueUpdate_Update interface {
	isQueueUpdate_Update()
}

type QueueUpdate_Started struct {
	Started *QueueStarted `protobuf:"bytes,2,opt,name=started,proto3,oneof"`
}

type QueueUpdate_Stopped struct {
	Stopped *QueueStopped `protobuf:"bytes,3,opt,name=stopped,proto3,oneof"`
}

type QueueUpdate_Found struct {
	Found *MatchFound `protobuf:"bytes,4,opt,name=found,proto3,oneof"`
}

func (*QueueUpdate_Started) isQueueUpdate_Update() {}

func (*QueueUpdate_Stopped) isQueueUpdate_Update() {}

func (*QueueUpdate_Found) isQueueUpdate_Update() {}

type QueueStarted struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Gamemode  string                 `protobuf:"bytes,1,opt,name=gamemode,proto3" json:"gamemode,omitempty"`
	StartTime *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
}

func (x *QueueStarted) Reset() {
	*x = QueueStarted{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quip_messages_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueueStarted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueStarted) ProtoMessage() {}

func (x *QueueStarted) ProtoReflect() protoreflect.Message {
	mi := &file_quip_messages_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueStarted.ProtoReflect.Descriptor instead.
func (*QueueStarted) Descriptor() ([]byte, []int) {
	return file_quip_messages_proto_rawDescGZIP(), []int{1}
}

func (x *QueueStarted) GetGamemode() string {
	if x != nil {
		return x.Gamemode
	}
	return ""
}

func (x *QueueStarted) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

type QueueStopped struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reason *string `protobuf:"bytes,1,opt,name=reason,proto3,oneof" json:"reason,omitempty"`
}

func (x *QueueStopped) Reset() {
	*x = QueueStopped{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quip_messages_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueueStopped) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueStopped) ProtoMessage() {}

func (x *QueueStopped) ProtoReflect() protoreflect.Message {
	mi := &file_quip_messages_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueStopped.ProtoReflect.Descriptor instead.
func (*QueueStopped) Descriptor() ([]byte, []int) {
	return file_quip_messages_proto_rawDescGZIP(), []int{2}
}

func (x *QueueStopped) GetReason() string {
	if x != nil && x.Reason != nil {
		return *x.Reason
	}
	return ""
}

type MatchFound struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Connection string `protobuf:"bytes,1,opt,name=connection,proto3" json:"connection,omitempty"`
}

func (x *MatchFound) Reset() {
	*x = MatchFound{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quip_messages_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MatchFound) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchFound) ProtoMessage() {}

func (x *MatchFound) ProtoReflect() protoreflect.Message {
	mi := &file_quip_messages_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchFound.ProtoReflect.Descriptor instead.
func (*MatchFound) Descriptor() ([]byte, []int) {
	return file_quip_messages_proto_rawDescGZIP(), []int{3}
}

func (x *MatchFound) GetConnection() string {
	if x != nil {
		return x.Connection
	}
	return ""
}

// Indicates change in status.
type StatusUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Targets []string `protobuf:"bytes,1,rep,name=targets,proto3" json:"targets,omitempty"`
	Status  Status   `protobuf:"varint,2,opt,name=status,proto3,enum=quip.Status" json:"status,omitempty"`
}

func (x *StatusUpdate) Reset() {
	*x = StatusUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quip_messages_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatusUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusUpdate) ProtoMessage() {}

func (x *StatusUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_quip_messages_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusUpdate.ProtoReflect.Descriptor instead.
func (*StatusUpdate) Descriptor() ([]byte, []int) {
	return file_quip_messages_proto_rawDescGZIP(), []int{4}
}

func (x *StatusUpdate) GetTargets() []string {
	if x != nil {
		return x.Targets
	}
	return nil
}

func (x *StatusUpdate) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_OFFLINE
}

var File_quip_messages_proto protoreflect.FileDescriptor

var file_quip_messages_proto_rawDesc = []byte{
	0x0a, 0x13, 0x71, 0x75, 0x69, 0x70, 0x2d, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x71, 0x75, 0x69, 0x70, 0x1a, 0x1f, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xbb, 0x01, 0x0a,
	0x0b, 0x51, 0x75, 0x65, 0x75, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x74,
	0x61, 0x72, 0x67, 0x65, 0x74, 0x73, 0x12, 0x2e, 0x0a, 0x07, 0x73, 0x74, 0x61, 0x72, 0x74, 0x65,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x71, 0x75, 0x69, 0x70, 0x2e, 0x51,
	0x75, 0x65, 0x75, 0x65, 0x53, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x48, 0x00, 0x52, 0x07, 0x73,
	0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x12, 0x2e, 0x0a, 0x07, 0x73, 0x74, 0x6f, 0x70, 0x70, 0x65,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x71, 0x75, 0x69, 0x70, 0x2e, 0x51,
	0x75, 0x65, 0x75, 0x65, 0x53, 0x74, 0x6f, 0x70, 0x70, 0x65, 0x64, 0x48, 0x00, 0x52, 0x07, 0x73,
	0x74, 0x6f, 0x70, 0x70, 0x65, 0x64, 0x12, 0x28, 0x0a, 0x05, 0x66, 0x6f, 0x75, 0x6e, 0x64, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x71, 0x75, 0x69, 0x70, 0x2e, 0x4d, 0x61, 0x74,
	0x63, 0x68, 0x46, 0x6f, 0x75, 0x6e, 0x64, 0x48, 0x00, 0x52, 0x05, 0x66, 0x6f, 0x75, 0x6e, 0x64,
	0x42, 0x08, 0x0a, 0x06, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x22, 0x65, 0x0a, 0x0c, 0x51, 0x75,
	0x65, 0x75, 0x65, 0x53, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x67, 0x61,
	0x6d, 0x65, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x67, 0x61,
	0x6d, 0x65, 0x6d, 0x6f, 0x64, 0x65, 0x12, 0x39, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f,
	0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d,
	0x65, 0x22, 0x36, 0x0a, 0x0c, 0x51, 0x75, 0x65, 0x75, 0x65, 0x53, 0x74, 0x6f, 0x70, 0x70, 0x65,
	0x64, 0x12, 0x1b, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x48, 0x00, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x88, 0x01, 0x01, 0x42, 0x09,
	0x0a, 0x07, 0x5f, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x22, 0x2c, 0x0a, 0x0a, 0x4d, 0x61, 0x74,
	0x63, 0x68, 0x46, 0x6f, 0x75, 0x6e, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x6f, 0x6e, 0x6e, 0x65,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x6f, 0x6e,
	0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x4e, 0x0a, 0x0c, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x61, 0x72, 0x67, 0x65,
	0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74,
	0x73, 0x12, 0x24, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x0c, 0x2e, 0x71, 0x75, 0x69, 0x70, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2a, 0x3b, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x0b, 0x0a, 0x07, 0x4f, 0x46, 0x46, 0x4c, 0x49, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x08,
	0x0a, 0x04, 0x49, 0x44, 0x4c, 0x45, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x53, 0x45, 0x41, 0x52,
	0x43, 0x48, 0x49, 0x4e, 0x47, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x50, 0x4c, 0x41, 0x59, 0x49,
	0x4e, 0x47, 0x10, 0x03, 0x42, 0x23, 0x5a, 0x21, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x47, 0x61, 0x6d, 0x62, 0x69, 0x74, 0x4c, 0x4c, 0x43, 0x2f, 0x71, 0x75, 0x69,
	0x70, 0x2f, 0x6c, 0x69, 0x62, 0x73, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_quip_messages_proto_rawDescOnce sync.Once
	file_quip_messages_proto_rawDescData = file_quip_messages_proto_rawDesc
)

func file_quip_messages_proto_rawDescGZIP() []byte {
	file_quip_messages_proto_rawDescOnce.Do(func() {
		file_quip_messages_proto_rawDescData = protoimpl.X.CompressGZIP(file_quip_messages_proto_rawDescData)
	})
	return file_quip_messages_proto_rawDescData
}

var file_quip_messages_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_quip_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_quip_messages_proto_goTypes = []interface{}{
	(Status)(0),                   // 0: quip.Status
	(*QueueUpdate)(nil),           // 1: quip.QueueUpdate
	(*QueueStarted)(nil),          // 2: quip.QueueStarted
	(*QueueStopped)(nil),          // 3: quip.QueueStopped
	(*MatchFound)(nil),            // 4: quip.MatchFound
	(*StatusUpdate)(nil),          // 5: quip.StatusUpdate
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_quip_messages_proto_depIdxs = []int32{
	2, // 0: quip.QueueUpdate.started:type_name -> quip.QueueStarted
	3, // 1: quip.QueueUpdate.stopped:type_name -> quip.QueueStopped
	4, // 2: quip.QueueUpdate.found:type_name -> quip.MatchFound
	6, // 3: quip.QueueStarted.start_time:type_name -> google.protobuf.Timestamp
	0, // 4: quip.StatusUpdate.status:type_name -> quip.Status
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_quip_messages_proto_init() }
func file_quip_messages_proto_init() {
	if File_quip_messages_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_quip_messages_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueueUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_quip_messages_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueueStarted); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_quip_messages_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueueStopped); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_quip_messages_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MatchFound); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_quip_messages_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatusUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_quip_messages_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*QueueUpdate_Started)(nil),
		(*QueueUpdate_Stopped)(nil),
		(*QueueUpdate_Found)(nil),
	}
	file_quip_messages_proto_msgTypes[2].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_quip_messages_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_quip_messages_proto_goTypes,
		DependencyIndexes: file_quip_messages_proto_depIdxs,
		EnumInfos:         file_quip_messages_proto_enumTypes,
		MessageInfos:      file_quip_messages_proto_msgTypes,
	}.Build()
	File_quip_messages_proto = out.File
	file_quip_messages_proto_rawDesc = nil
	file_quip_messages_proto_goTypes = nil
	file_quip_messages_proto_depIdxs = nil
}
