// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.29.1
// 	protoc        v3.21.12
// source: quip-messages.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MatchState int32

const (
	MatchState_MATCH_PENDING  MatchState = 0 // Match has been allocated and is waiting for connections.
	MatchState_MATCH_PLAYING  MatchState = 1 // Match is in progress.
	MatchState_MATCH_FINISHED MatchState = 2 // Match has completed.
)

// Enum value maps for MatchState.
var (
	MatchState_name = map[int32]string{
		0: "MATCH_PENDING",
		1: "MATCH_PLAYING",
		2: "MATCH_FINISHED",
	}
	MatchState_value = map[string]int32{
		"MATCH_PENDING":  0,
		"MATCH_PLAYING":  1,
		"MATCH_FINISHED": 2,
	}
)

func (x MatchState) Enum() *MatchState {
	p := new(MatchState)
	*p = x
	return p
}

func (x MatchState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MatchState) Descriptor() protoreflect.EnumDescriptor {
	return file_quip_messages_proto_enumTypes[0].Descriptor()
}

func (MatchState) Type() protoreflect.EnumType {
	return &file_quip_messages_proto_enumTypes[0]
}

func (x MatchState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MatchState.Descriptor instead.
func (MatchState) EnumDescriptor() ([]byte, []int) {
	return file_quip_messages_proto_rawDescGZIP(), []int{0}
}

type Status int32

const (
	Status_OFFLINE   Status = 0
	Status_IDLE      Status = 1
	Status_SEARCHING Status = 2
	Status_PLAYING   Status = 3
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "OFFLINE",
		1: "IDLE",
		2: "SEARCHING",
		3: "PLAYING",
	}
	Status_value = map[string]int32{
		"OFFLINE":   0,
		"IDLE":      1,
		"SEARCHING": 2,
		"PLAYING":   3,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_quip_messages_proto_enumTypes[1].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_quip_messages_proto_enumTypes[1]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_quip_messages_proto_rawDescGZIP(), []int{1}
}

// Indicates change in queue status.
type QueueUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Identifies the entities whose queue has received an update.
	Targets []string `protobuf:"bytes,1,rep,name=targets,proto3" json:"targets,omitempty"`
	// Types that are assignable to Update:
	//
	//	*QueueUpdate_Started
	//	*QueueUpdate_Stopped
	//	*QueueUpdate_Found
	Update isQueueUpdate_Update `protobuf_oneof:"update"`
}

func (x *QueueUpdate) Reset() {
	*x = QueueUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quip_messages_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueueUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueUpdate) ProtoMessage() {}

func (x *QueueUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_quip_messages_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueUpdate.ProtoReflect.Descriptor instead.
func (*QueueUpdate) Descriptor() ([]byte, []int) {
	return file_quip_messages_proto_rawDescGZIP(), []int{0}
}

func (x *QueueUpdate) GetTargets() []string {
	if x != nil {
		return x.Targets
	}
	return nil
}

func (m *QueueUpdate) GetUpdate() isQueueUpdate_Update {
	if m != nil {
		return m.Update
	}
	return nil
}

func (x *QueueUpdate) GetStarted() *QueueDetails {
	if x, ok := x.GetUpdate().(*QueueUpdate_Started); ok {
		return x.Started
	}
	return nil
}

func (x *QueueUpdate) GetStopped() string {
	if x, ok := x.GetUpdate().(*QueueUpdate_Stopped); ok {
		return x.Stopped
	}
	return ""
}

func (x *QueueUpdate) GetFound() *MatchDetails {
	if x, ok := x.GetUpdate().(*QueueUpdate_Found); ok {
		return x.Found
	}
	return nil
}

type isQueueUpdate_Update interface {
	isQueueUpdate_Update()
}

type QueueUpdate_Started struct {
	Started *QueueDetails `protobuf:"bytes,2,opt,name=started,proto3,oneof"`
}

type QueueUpdate_Stopped struct {
	Stopped string `protobuf:"bytes,3,opt,name=stopped,proto3,oneof"`
}

type QueueUpdate_Found struct {
	Found *MatchDetails `protobuf:"bytes,4,opt,name=found,proto3,oneof"`
}

func (*QueueUpdate_Started) isQueueUpdate_Update() {}

func (*QueueUpdate_Stopped) isQueueUpdate_Update() {}

func (*QueueUpdate_Found) isQueueUpdate_Update() {}

type QueueDetails struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Gamemode  string                 `protobuf:"bytes,1,opt,name=gamemode,proto3" json:"gamemode,omitempty"`
	StartTime *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
}

func (x *QueueDetails) Reset() {
	*x = QueueDetails{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quip_messages_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueueDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueDetails) ProtoMessage() {}

func (x *QueueDetails) ProtoReflect() protoreflect.Message {
	mi := &file_quip_messages_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueDetails.ProtoReflect.Descriptor instead.
func (*QueueDetails) Descriptor() ([]byte, []int) {
	return file_quip_messages_proto_rawDescGZIP(), []int{1}
}

func (x *QueueDetails) GetGamemode() string {
	if x != nil {
		return x.Gamemode
	}
	return ""
}

func (x *QueueDetails) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

type MatchDetails struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Connection string     `protobuf:"bytes,2,opt,name=connection,proto3" json:"connection,omitempty"`
	State      MatchState `protobuf:"varint,3,opt,name=state,proto3,enum=quip.MatchState" json:"state,omitempty"`
}

func (x *MatchDetails) Reset() {
	*x = MatchDetails{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quip_messages_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MatchDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchDetails) ProtoMessage() {}

func (x *MatchDetails) ProtoReflect() protoreflect.Message {
	mi := &file_quip_messages_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchDetails.ProtoReflect.Descriptor instead.
func (*MatchDetails) Descriptor() ([]byte, []int) {
	return file_quip_messages_proto_rawDescGZIP(), []int{2}
}

func (x *MatchDetails) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MatchDetails) GetConnection() string {
	if x != nil {
		return x.Connection
	}
	return ""
}

func (x *MatchDetails) GetState() MatchState {
	if x != nil {
		return x.State
	}
	return MatchState_MATCH_PENDING
}

// Indicates change in status.
type StatusUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Targets []string `protobuf:"bytes,1,rep,name=targets,proto3" json:"targets,omitempty"`
	Status  Status   `protobuf:"varint,2,opt,name=status,proto3,enum=quip.Status" json:"status,omitempty"`
}

func (x *StatusUpdate) Reset() {
	*x = StatusUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quip_messages_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatusUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusUpdate) ProtoMessage() {}

func (x *StatusUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_quip_messages_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusUpdate.ProtoReflect.Descriptor instead.
func (*StatusUpdate) Descriptor() ([]byte, []int) {
	return file_quip_messages_proto_rawDescGZIP(), []int{3}
}

func (x *StatusUpdate) GetTargets() []string {
	if x != nil {
		return x.Targets
	}
	return nil
}

func (x *StatusUpdate) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_OFFLINE
}

var File_quip_messages_proto protoreflect.FileDescriptor

var file_quip_messages_proto_rawDesc = []byte{
	0x0a, 0x13, 0x71, 0x75, 0x69, 0x70, 0x2d, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x71, 0x75, 0x69, 0x70, 0x1a, 0x1f, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa9, 0x01, 0x0a,
	0x0b, 0x51, 0x75, 0x65, 0x75, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x74,
	0x61, 0x72, 0x67, 0x65, 0x74, 0x73, 0x12, 0x2e, 0x0a, 0x07, 0x73, 0x74, 0x61, 0x72, 0x74, 0x65,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x71, 0x75, 0x69, 0x70, 0x2e, 0x51,
	0x75, 0x65, 0x75, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x48, 0x00, 0x52, 0x07, 0x73,
	0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x12, 0x1a, 0x0a, 0x07, 0x73, 0x74, 0x6f, 0x70, 0x70, 0x65,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x07, 0x73, 0x74, 0x6f, 0x70, 0x70,
	0x65, 0x64, 0x12, 0x2a, 0x0a, 0x05, 0x66, 0x6f, 0x75, 0x6e, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x12, 0x2e, 0x71, 0x75, 0x69, 0x70, 0x2e, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x44, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x73, 0x48, 0x00, 0x52, 0x05, 0x66, 0x6f, 0x75, 0x6e, 0x64, 0x42, 0x08,
	0x0a, 0x06, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x22, 0x65, 0x0a, 0x0c, 0x51, 0x75, 0x65, 0x75,
	0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x67, 0x61, 0x6d, 0x65,
	0x6d, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x67, 0x61, 0x6d, 0x65,
	0x6d, 0x6f, 0x64, 0x65, 0x12, 0x39, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x74, 0x69,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x22,
	0x66, 0x0a, 0x0c, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x1e, 0x0a, 0x0a, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x26, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10,
	0x2e, 0x71, 0x75, 0x69, 0x70, 0x2e, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x22, 0x4e, 0x0a, 0x0c, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x61, 0x72, 0x67, 0x65,
	0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74,
	0x73, 0x12, 0x24, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x0c, 0x2e, 0x71, 0x75, 0x69, 0x70, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2a, 0x46, 0x0a, 0x0a, 0x4d, 0x61, 0x74, 0x63, 0x68,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x11, 0x0a, 0x0d, 0x4d, 0x41, 0x54, 0x43, 0x48, 0x5f, 0x50,
	0x45, 0x4e, 0x44, 0x49, 0x4e, 0x47, 0x10, 0x00, 0x12, 0x11, 0x0a, 0x0d, 0x4d, 0x41, 0x54, 0x43,
	0x48, 0x5f, 0x50, 0x4c, 0x41, 0x59, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x12, 0x12, 0x0a, 0x0e, 0x4d,
	0x41, 0x54, 0x43, 0x48, 0x5f, 0x46, 0x49, 0x4e, 0x49, 0x53, 0x48, 0x45, 0x44, 0x10, 0x02, 0x2a,
	0x3b, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0b, 0x0a, 0x07, 0x4f, 0x46, 0x46,
	0x4c, 0x49, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x49, 0x44, 0x4c, 0x45, 0x10, 0x01,
	0x12, 0x0d, 0x0a, 0x09, 0x53, 0x45, 0x41, 0x52, 0x43, 0x48, 0x49, 0x4e, 0x47, 0x10, 0x02, 0x12,
	0x0b, 0x0a, 0x07, 0x50, 0x4c, 0x41, 0x59, 0x49, 0x4e, 0x47, 0x10, 0x03, 0x42, 0x23, 0x5a, 0x21,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x47, 0x61, 0x6d, 0x62, 0x69,
	0x74, 0x4c, 0x4c, 0x43, 0x2f, 0x71, 0x75, 0x69, 0x70, 0x2f, 0x6c, 0x69, 0x62, 0x73, 0x2f, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_quip_messages_proto_rawDescOnce sync.Once
	file_quip_messages_proto_rawDescData = file_quip_messages_proto_rawDesc
)

func file_quip_messages_proto_rawDescGZIP() []byte {
	file_quip_messages_proto_rawDescOnce.Do(func() {
		file_quip_messages_proto_rawDescData = protoimpl.X.CompressGZIP(file_quip_messages_proto_rawDescData)
	})
	return file_quip_messages_proto_rawDescData
}

var file_quip_messages_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_quip_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_quip_messages_proto_goTypes = []interface{}{
	(MatchState)(0),               // 0: quip.MatchState
	(Status)(0),                   // 1: quip.Status
	(*QueueUpdate)(nil),           // 2: quip.QueueUpdate
	(*QueueDetails)(nil),          // 3: quip.QueueDetails
	(*MatchDetails)(nil),          // 4: quip.MatchDetails
	(*StatusUpdate)(nil),          // 5: quip.StatusUpdate
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_quip_messages_proto_depIdxs = []int32{
	3, // 0: quip.QueueUpdate.started:type_name -> quip.QueueDetails
	4, // 1: quip.QueueUpdate.found:type_name -> quip.MatchDetails
	6, // 2: quip.QueueDetails.start_time:type_name -> google.protobuf.Timestamp
	0, // 3: quip.MatchDetails.state:type_name -> quip.MatchState
	1, // 4: quip.StatusUpdate.status:type_name -> quip.Status
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_quip_messages_proto_init() }
func file_quip_messages_proto_init() {
	if File_quip_messages_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_quip_messages_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueueUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_quip_messages_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueueDetails); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_quip_messages_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MatchDetails); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_quip_messages_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatusUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_quip_messages_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*QueueUpdate_Started)(nil),
		(*QueueUpdate_Stopped)(nil),
		(*QueueUpdate_Found)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_quip_messages_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_quip_messages_proto_goTypes,
		DependencyIndexes: file_quip_messages_proto_depIdxs,
		EnumInfos:         file_quip_messages_proto_enumTypes,
		MessageInfos:      file_quip_messages_proto_msgTypes,
	}.Build()
	File_quip_messages_proto = out.File
	file_quip_messages_proto_rawDesc = nil
	file_quip_messages_proto_goTypes = nil
	file_quip_messages_proto_depIdxs = nil
}
