// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Profile struct {
	Username string     `json:"username"`
	Dob      *time.Time `json:"dob,omitempty"`
}

type User struct {
	ID      string   `json:"id"`
	Profile *Profile `json:"profile"`
}
