// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type StatusDetails interface {
	IsStatusDetails()
}

type Profile struct {
	Username string     `json:"username"`
	Dob      *time.Time `json:"dob,omitempty"`
}
