// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Profile struct {
	Username string `json:"username"`
	Dob      *Date  `json:"dob,omitempty"`
}

type User struct {
	ID      string   `json:"id"`
	Profile *Profile `json:"profile"`
}
