auth:
  issuer: http://localhost
  audience: http://localhost
  jwks_uri: http://localhost
api:
  matchmaker:
    hostname: localhost
    port: 50051
  socket_io-server:
    hostname: localhost
    port: 3000
redis:
  hostname: localhost
  port: 6379
openmatch:
  frontend:
    hostname: localhost
    port: 50504
