auth:
  issuer: http://quip.gg
  audience: http://quip.gg
  jwks_uri: http://quip.gg

api:
  graph:
    hostname:
    port: 8080
  tls:
    certificateFile:
    privateKeyFile:
    rootCertificateFile:

matchmaker:
  frontend:
    hostname:
    port: 50051
  backend:
    hostname:
    port: 50052
  matchfunction:
    hostname:
    port: 50059
  redis:
    hostname:
    port: 6379

sockets:
  server:
    hostname:
    port: 3000
  redis:
    hostname:
    port: 6379

broker:
  hostname:
  port: 6379

openmatch:
  backend:
    hostname:
    port: 50505
  frontend:
    hostname:
    port: 50504
  query:
    hostname:
    port: 50503

agones:
  hostname:
  port:
