auth:
  issuer: http://localhost
  audience: http://localhost
  jwks_uri: http://localhost
matchmaker:
  frontend:
    hostname: localhost
    port: 50051
  matchfunction:
    hostname: localhost
    port: 50052
  redis:
    hostname: localhost
    port: 6379
sockets:
  server:
    hostname: localhost
    port: 3000
  redis:
    hostname: localhost
    port: 6379
broker:
  hostname: localhost
  port: 6379
openmatch:
  frontend:
    hostname: localhost
    port: 50504
