// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: libs/matchmaker/internal/api/messages.proto

package ipb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MatchInternal_State int32

const (
	MatchInternal_STATE_UNSPECIFIED MatchInternal_State = 0
	MatchInternal_STATE_PENDING     MatchInternal_State = 1
	MatchInternal_STATE_PLAYING     MatchInternal_State = 2
	MatchInternal_STATE_FINISHED    MatchInternal_State = 3
)

// Enum value maps for MatchInternal_State.
var (
	MatchInternal_State_name = map[int32]string{
		0: "STATE_UNSPECIFIED",
		1: "STATE_PENDING",
		2: "STATE_PLAYING",
		3: "STATE_FINISHED",
	}
	MatchInternal_State_value = map[string]int32{
		"STATE_UNSPECIFIED": 0,
		"STATE_PENDING":     1,
		"STATE_PLAYING":     2,
		"STATE_FINISHED":    3,
	}
)

func (x MatchInternal_State) Enum() *MatchInternal_State {
	p := new(MatchInternal_State)
	*p = x
	return p
}

func (x MatchInternal_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MatchInternal_State) Descriptor() protoreflect.EnumDescriptor {
	return file_libs_matchmaker_internal_api_messages_proto_enumTypes[0].Descriptor()
}

func (MatchInternal_State) Type() protoreflect.EnumType {
	return &file_libs_matchmaker_internal_api_messages_proto_enumTypes[0]
}

func (x MatchInternal_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MatchInternal_State.Descriptor instead.
func (MatchInternal_State) EnumDescriptor() ([]byte, []int) {
	return file_libs_matchmaker_internal_api_messages_proto_rawDescGZIP(), []int{3, 0}
}

// Internal message for holding relevant player information.
type PlayerInternal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerId string  `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	TicketId *string `protobuf:"bytes,2,opt,name=ticket_id,json=ticketId,proto3,oneof" json:"ticket_id,omitempty"`
	MatchId  *string `protobuf:"bytes,3,opt,name=match_id,json=matchId,proto3,oneof" json:"match_id,omitempty"`
}

func (x *PlayerInternal) Reset() {
	*x = PlayerInternal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_libs_matchmaker_internal_api_messages_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerInternal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerInternal) ProtoMessage() {}

func (x *PlayerInternal) ProtoReflect() protoreflect.Message {
	mi := &file_libs_matchmaker_internal_api_messages_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerInternal.ProtoReflect.Descriptor instead.
func (*PlayerInternal) Descriptor() ([]byte, []int) {
	return file_libs_matchmaker_internal_api_messages_proto_rawDescGZIP(), []int{0}
}

func (x *PlayerInternal) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *PlayerInternal) GetTicketId() string {
	if x != nil && x.TicketId != nil {
		return *x.TicketId
	}
	return ""
}

func (x *PlayerInternal) GetMatchId() string {
	if x != nil && x.MatchId != nil {
		return *x.MatchId
	}
	return ""
}

// Internal message for holding relevant ticket information.
type TicketInternal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerId string `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Gamemode string `protobuf:"bytes,2,opt,name=gamemode,proto3" json:"gamemode,omitempty"`
}

func (x *TicketInternal) Reset() {
	*x = TicketInternal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_libs_matchmaker_internal_api_messages_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TicketInternal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TicketInternal) ProtoMessage() {}

func (x *TicketInternal) ProtoReflect() protoreflect.Message {
	mi := &file_libs_matchmaker_internal_api_messages_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TicketInternal.ProtoReflect.Descriptor instead.
func (*TicketInternal) Descriptor() ([]byte, []int) {
	return file_libs_matchmaker_internal_api_messages_proto_rawDescGZIP(), []int{1}
}

func (x *TicketInternal) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *TicketInternal) GetGamemode() string {
	if x != nil {
		return x.Gamemode
	}
	return ""
}

// Internal message for holding relevant game information.
type GameDetails struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Name of the current gamemode.
	Gamemode string `protobuf:"bytes,1,opt,name=gamemode,proto3" json:"gamemode,omitempty"`
	// Number of teams in the match.
	Teams uint32 `protobuf:"varint,2,opt,name=teams,proto3" json:"teams,omitempty"`
	// Number of players per team.
	Players uint32 `protobuf:"varint,3,opt,name=players,proto3" json:"players,omitempty"`
}

func (x *GameDetails) Reset() {
	*x = GameDetails{}
	if protoimpl.UnsafeEnabled {
		mi := &file_libs_matchmaker_internal_api_messages_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameDetails) ProtoMessage() {}

func (x *GameDetails) ProtoReflect() protoreflect.Message {
	mi := &file_libs_matchmaker_internal_api_messages_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameDetails.ProtoReflect.Descriptor instead.
func (*GameDetails) Descriptor() ([]byte, []int) {
	return file_libs_matchmaker_internal_api_messages_proto_rawDescGZIP(), []int{2}
}

func (x *GameDetails) GetGamemode() string {
	if x != nil {
		return x.Gamemode
	}
	return ""
}

func (x *GameDetails) GetTeams() uint32 {
	if x != nil {
		return x.Teams
	}
	return 0
}

func (x *GameDetails) GetPlayers() uint32 {
	if x != nil {
		return x.Players
	}
	return 0
}

type MatchInternal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MatchId    string              `protobuf:"bytes,1,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	Connection string              `protobuf:"bytes,2,opt,name=connection,proto3" json:"connection,omitempty"`
	State      MatchInternal_State `protobuf:"varint,3,opt,name=state,proto3,enum=quip.matchmaker.internal.MatchInternal_State" json:"state,omitempty"`
}

func (x *MatchInternal) Reset() {
	*x = MatchInternal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_libs_matchmaker_internal_api_messages_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MatchInternal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchInternal) ProtoMessage() {}

func (x *MatchInternal) ProtoReflect() protoreflect.Message {
	mi := &file_libs_matchmaker_internal_api_messages_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchInternal.ProtoReflect.Descriptor instead.
func (*MatchInternal) Descriptor() ([]byte, []int) {
	return file_libs_matchmaker_internal_api_messages_proto_rawDescGZIP(), []int{3}
}

func (x *MatchInternal) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

func (x *MatchInternal) GetConnection() string {
	if x != nil {
		return x.Connection
	}
	return ""
}

func (x *MatchInternal) GetState() MatchInternal_State {
	if x != nil {
		return x.State
	}
	return MatchInternal_STATE_UNSPECIFIED
}

var File_libs_matchmaker_internal_api_messages_proto protoreflect.FileDescriptor

var file_libs_matchmaker_internal_api_messages_proto_rawDesc = []byte{
	0x0a, 0x2b, 0x6c, 0x69, 0x62, 0x73, 0x2f, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x6d, 0x61, 0x6b, 0x65,
	0x72, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x18, 0x71,
	0x75, 0x69, 0x70, 0x2e, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x6d, 0x61, 0x6b, 0x65, 0x72, 0x2e, 0x69,
	0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x22, 0x8a, 0x01, 0x0a, 0x0e, 0x50, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x09, 0x74, 0x69, 0x63, 0x6b, 0x65,
	0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x08, 0x74, 0x69,
	0x63, 0x6b, 0x65, 0x74, 0x49, 0x64, 0x88, 0x01, 0x01, 0x12, 0x1e, 0x0a, 0x08, 0x6d, 0x61, 0x74,
	0x63, 0x68, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x07, 0x6d,
	0x61, 0x74, 0x63, 0x68, 0x49, 0x64, 0x88, 0x01, 0x01, 0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x74, 0x69,
	0x63, 0x6b, 0x65, 0x74, 0x5f, 0x69, 0x64, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x6d, 0x61, 0x74, 0x63,
	0x68, 0x5f, 0x69, 0x64, 0x22, 0x49, 0x0a, 0x0e, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x49, 0x6e,
	0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x67, 0x61, 0x6d, 0x65, 0x6d, 0x6f, 0x64, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x67, 0x61, 0x6d, 0x65, 0x6d, 0x6f, 0x64, 0x65, 0x22,
	0x59, 0x0a, 0x0b, 0x47, 0x61, 0x6d, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x1a,
	0x0a, 0x08, 0x67, 0x61, 0x6d, 0x65, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x67, 0x61, 0x6d, 0x65, 0x6d, 0x6f, 0x64, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x65,
	0x61, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x74, 0x65, 0x61, 0x6d, 0x73,
	0x12, 0x18, 0x0a, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x22, 0xe9, 0x01, 0x0a, 0x0d, 0x4d,
	0x61, 0x74, 0x63, 0x68, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x12, 0x19, 0x0a, 0x08,
	0x6d, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6d, 0x61, 0x74, 0x63, 0x68, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x6f, 0x6e, 0x6e, 0x65,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x6f, 0x6e,
	0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x43, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x2d, 0x2e, 0x71, 0x75, 0x69, 0x70, 0x2e, 0x6d, 0x61,
	0x74, 0x63, 0x68, 0x6d, 0x61, 0x6b, 0x65, 0x72, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61,
	0x6c, 0x2e, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2e,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x22, 0x58, 0x0a, 0x05,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x15, 0x0a, 0x11, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x55,
	0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x11, 0x0a, 0x0d,
	0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x50, 0x45, 0x4e, 0x44, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x12,
	0x11, 0x0a, 0x0d, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x50, 0x4c, 0x41, 0x59, 0x49, 0x4e, 0x47,
	0x10, 0x02, 0x12, 0x12, 0x0a, 0x0e, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x46, 0x49, 0x4e, 0x49,
	0x53, 0x48, 0x45, 0x44, 0x10, 0x03, 0x42, 0x38, 0x5a, 0x36, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x47, 0x61, 0x6d, 0x62, 0x69, 0x74, 0x4c, 0x4c, 0x43, 0x2f, 0x71,
	0x75, 0x69, 0x70, 0x2f, 0x6c, 0x69, 0x62, 0x73, 0x2f, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x6d, 0x61,
	0x6b, 0x65, 0x72, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x69, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_libs_matchmaker_internal_api_messages_proto_rawDescOnce sync.Once
	file_libs_matchmaker_internal_api_messages_proto_rawDescData = file_libs_matchmaker_internal_api_messages_proto_rawDesc
)

func file_libs_matchmaker_internal_api_messages_proto_rawDescGZIP() []byte {
	file_libs_matchmaker_internal_api_messages_proto_rawDescOnce.Do(func() {
		file_libs_matchmaker_internal_api_messages_proto_rawDescData = protoimpl.X.CompressGZIP(file_libs_matchmaker_internal_api_messages_proto_rawDescData)
	})
	return file_libs_matchmaker_internal_api_messages_proto_rawDescData
}

var file_libs_matchmaker_internal_api_messages_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_libs_matchmaker_internal_api_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_libs_matchmaker_internal_api_messages_proto_goTypes = []interface{}{
	(MatchInternal_State)(0), // 0: quip.matchmaker.internal.MatchInternal.State
	(*PlayerInternal)(nil),   // 1: quip.matchmaker.internal.PlayerInternal
	(*TicketInternal)(nil),   // 2: quip.matchmaker.internal.TicketInternal
	(*GameDetails)(nil),      // 3: quip.matchmaker.internal.GameDetails
	(*MatchInternal)(nil),    // 4: quip.matchmaker.internal.MatchInternal
}
var file_libs_matchmaker_internal_api_messages_proto_depIdxs = []int32{
	0, // 0: quip.matchmaker.internal.MatchInternal.state:type_name -> quip.matchmaker.internal.MatchInternal.State
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_libs_matchmaker_internal_api_messages_proto_init() }
func file_libs_matchmaker_internal_api_messages_proto_init() {
	if File_libs_matchmaker_internal_api_messages_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_libs_matchmaker_internal_api_messages_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerInternal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_libs_matchmaker_internal_api_messages_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TicketInternal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_libs_matchmaker_internal_api_messages_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameDetails); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_libs_matchmaker_internal_api_messages_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MatchInternal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_libs_matchmaker_internal_api_messages_proto_msgTypes[0].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_libs_matchmaker_internal_api_messages_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_libs_matchmaker_internal_api_messages_proto_goTypes,
		DependencyIndexes: file_libs_matchmaker_internal_api_messages_proto_depIdxs,
		EnumInfos:         file_libs_matchmaker_internal_api_messages_proto_enumTypes,
		MessageInfos:      file_libs_matchmaker_internal_api_messages_proto_msgTypes,
	}.Build()
	File_libs_matchmaker_internal_api_messages_proto = out.File
	file_libs_matchmaker_internal_api_messages_proto_rawDesc = nil
	file_libs_matchmaker_internal_api_messages_proto_goTypes = nil
	file_libs_matchmaker_internal_api_messages_proto_depIdxs = nil
}
